// src/lib/course/templates/mathB/sequence_ct_geometric_word_basic.ts
import type { QuestionTemplate } from "../../types";
import { gradeNumeric } from "../_shared/utils";

type GeoCase = {
  id: string;
  title: string;
  a1: number;
  r: number;
  n: number;
  ask: "term" | "sum";
  context: string;
  difficulty: 1 | 2 | 3;
};

function buildTemplate(c: GeoCase): QuestionTemplate {
  const an = Math.round(c.a1 * Math.pow(c.r, c.n - 1) * 1000) / 1000;
  const sumRaw =
    c.r === 1 ? c.a1 * c.n : (c.a1 * (1 - Math.pow(c.r, c.n))) / (1 - c.r);
  const sum = Math.round(sumRaw * 1000) / 1000;
  const answer = c.ask === "sum" ? sum : an;
  const suffix =
    c.ask === "sum" ? `${c.n}回（または${c.n}日間）の合計を求めよ。` : `${c.n}回目（または${c.n}日目）を求めよ。`;
  return {
    meta: {
      id: c.id,
      topicId: c.ask === "sum" ? "seq_geometric_sum_basic" : "seq_geometric_basic",
      title: c.title,
      difficulty: c.difficulty,
      tags: ["sequence", "geometric", "ct"],
    },
    generate() {
      return {
        templateId: c.id,
        statement: `${c.context}${suffix}`,
        answerKind: "numeric",
        params: {},
      };
    },
    grade(_params, userAnswer) {
      return gradeNumeric(userAnswer, answer);
    },
    explain() {
      return `### この問題の解説\n等比数列で $a_1=${c.a1},\\ r=${c.r}$。\n${
        c.ask === "sum"
          ? "和は $S_n=\\frac{a_1(1-r^n)}{1-r}$。"
          : "一般項は $a_n=a_1 r^{n-1}$。"
      }\n答えは **${answer}**。`;
    },
  };
}

const CASES: GeoCase[] = [
  {
    id: "seq_ct_geo_1",
    title: "増加 1",
    a1: 2,
    r: 3,
    n: 5,
    ask: "term",
    context: "細菌の数が初め2個で、1時間ごとに3倍になる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_2",
    title: "増加 2",
    a1: 5,
    r: 2,
    n: 4,
    ask: "sum",
    context: "毎月の売上が初月5万円で、以後毎月2倍になる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_3",
    title: "減少 1",
    a1: 160,
    r: 0.8,
    n: 4,
    ask: "term",
    context: "ある薬の量が初め160mgで、毎回80%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_4",
    title: "減少 2",
    a1: 1000,
    r: 0.5,
    n: 6,
    ask: "sum",
    context: "毎回の削減量が初回1000円で、以後半分ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_5",
    title: "複利 1",
    a1: 100,
    r: 1.1,
    n: 3,
    ask: "term",
    context: "投資額が初め100万円で、年ごとに10%増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_6",
    title: "減衰 1",
    a1: 90,
    r: 0.75,
    n: 5,
    ask: "term",
    context: "ある音の強さが初め90で、毎回75%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_7",
    title: "積立 1",
    a1: 3,
    r: 2,
    n: 6,
    ask: "sum",
    context: "貯金額が初回3万円で、以後毎回2倍ずつ増える。",
    difficulty: 3,
  },
  {
    id: "seq_ct_geo_8",
    title: "減衰 2",
    a1: 200,
    r: 0.6,
    n: 4,
    ask: "term",
    context: "ある在庫が初め200個で、毎回60%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_9",
    title: "複利 2",
    a1: 50,
    r: 1.05,
    n: 4,
    ask: "term",
    context: "投資額が初め50万円で、年ごとに5%増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_10",
    title: "減衰 3",
    a1: 500,
    r: 0.7,
    n: 3,
    ask: "term",
    context: "放射量が初め500で、毎回70%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_11",
    title: "増加 3",
    a1: 4,
    r: 2,
    n: 6,
    ask: "term",
    context: "ある細胞の数が初め4個で、1時間ごとに2倍になる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_12",
    title: "減少 3",
    a1: 300,
    r: 0.5,
    n: 5,
    ask: "sum",
    context: "毎回の使用量が初回300gで、以後半分ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_13",
    title: "複利 3",
    a1: 80,
    r: 1.02,
    n: 5,
    ask: "term",
    context: "投資額が初め80万円で、年ごとに2%増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_14",
    title: "減衰 4",
    a1: 120,
    r: 0.8,
    n: 6,
    ask: "term",
    context: "ある物質量が初め120で、毎回80%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_15",
    title: "減少 5",
    a1: 8,
    r: 0.5,
    n: 5,
    ask: "sum",
    context: "毎回の使用量が初回8で、以後半分ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_16",
    title: "増加 4",
    a1: 6,
    r: 3,
    n: 4,
    ask: "term",
    context: "細菌の数が初め6個で、1時間ごとに3倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_17",
    title: "減衰 5",
    a1: 81,
    r: 1 / 3,
    n: 4,
    ask: "term",
    context: "量が初め81で、毎回1/3ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_18",
    title: "増加 5",
    a1: 2,
    r: 1.5,
    n: 5,
    ask: "term",
    context: "値が初め2で、毎回1.5倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_19",
    title: "減衰 6",
    a1: 100,
    r: 0.9,
    n: 4,
    ask: "term",
    context: "量が初め100で、毎回90%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_20",
    title: "増加 6",
    a1: 3,
    r: 2,
    n: 7,
    ask: "term",
    context: "細胞数が初め3個で、1時間ごとに2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_21",
    title: "減少 6",
    a1: 48,
    r: 2 / 3,
    n: 5,
    ask: "term",
    context: "量が初め48で、毎回2/3ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_22",
    title: "減少 7",
    a1: 27,
    r: 1 / 3,
    n: 5,
    ask: "sum",
    context: "毎回の使用量が初回27で、以後1/3ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_23",
    title: "増加 7",
    a1: 10,
    r: 1.5,
    n: 4,
    ask: "term",
    context: "値が初め10で、毎回1.5倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_24",
    title: "減衰 7",
    a1: 64,
    r: 0.5,
    n: 5,
    ask: "sum",
    context: "毎回の使用量が初回64で、以後半分ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_25",
    title: "増加 8",
    a1: 7,
    r: 2,
    n: 6,
    ask: "term",
    context: "数が初め7で、毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_26",
    title: "減衰 8",
    a1: 48,
    r: 0.5,
    n: 6,
    ask: "sum",
    context: "毎回の使用量が初回48で、以後半分ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_27",
    title: "増加 9",
    a1: 6,
    r: 1.5,
    n: 5,
    ask: "term",
    context: "値が初め6で、毎回1.5倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_28",
    title: "減少 8",
    a1: 81,
    r: 0.5,
    n: 5,
    ask: "term",
    context: "量が初め81で、毎回半分ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_29",
    title: "減衰 9",
    a1: 100,
    r: 0.8,
    n: 5,
    ask: "term",
    context: "量が初め100で、毎回80%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_30",
    title: "増加 10",
    a1: 5,
    r: 2,
    n: 7,
    ask: "term",
    context: "数が初め5で、毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_31",
    title: "減少 9",
    a1: 64,
    r: 0.5,
    n: 6,
    ask: "sum",
    context: "毎回の使用量が初回64で、以後半分ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_32",
    title: "増加 11",
    a1: 4,
    r: 2,
    n: 8,
    ask: "term",
    context: "数が初め4で、毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_33",
    title: "減衰 10",
    a1: 120,
    r: 0.8,
    n: 6,
    ask: "term",
    context: "量が初め120で、毎回80%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_34",
    title: "増加 12",
    a1: 3,
    r: 2,
    n: 9,
    ask: "term",
    context: "数が初め3で、毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_35",
    title: "減衰 11",
    a1: 72,
    r: 0.5,
    n: 6,
    ask: "sum",
    context: "毎回の使用量が初回72で、以後半分ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_36",
    title: "増加 13",
    a1: 5,
    r: 2,
    n: 9,
    ask: "term",
    context: "数が初め5で、毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_37",
    title: "減衰 12",
    a1: 80,
    r: 0.5,
    n: 7,
    ask: "sum",
    context: "毎回の使用量が初回80で、以後半分ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_38",
    title: "増加 14",
    a1: 6,
    r: 2,
    n: 10,
    ask: "term",
    context: "数が初め6で、毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_39",
    title: "減衰 13",
    a1: 96,
    r: 0.5,
    n: 7,
    ask: "sum",
    context: "毎回の使用量が初回96で、以後半分ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_40",
    title: "増加 15",
    a1: 5,
    r: 3,
    n: 6,
    ask: "term",
    context: "数が初め5で、毎回3倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_41",
    title: "減衰 14",
    a1: 128,
    r: 0.5,
    n: 6,
    ask: "sum",
    context: "毎回の使用量が初回128で、以後半分ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_42",
    title: "増加 16",
    a1: 3,
    r: 2,
    n: 9,
    ask: "term",
    context: "数が初め3で、毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_43",
    title: "減衰 15",
    a1: 60,
    r: 0.5,
    n: 5,
    ask: "sum",
    context: "毎回の使用量が初回60で、以後半分ずつになる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_44",
    title: "増加 17",
    a1: 8,
    r: 1.5,
    n: 7,
    ask: "term",
    context: "数が初め8で、毎回1.5倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_45",
    title: "減衰 16",
    a1: 81,
    r: 0.5,
    n: 6,
    ask: "sum",
    context: "毎回の使用量が初回81で、以後半分ずつになる。",
    difficulty: 2,
  },
];

export const sequenceCtGeometricWordTemplates: QuestionTemplate[] = CASES.map(buildTemplate);
