// src/lib/course/templates/mathB/sequence_ct_word_change_basic.ts
import type { QuestionTemplate } from "../../types";
import { gradeNumeric } from "../_shared/utils";

type ChangeCase = {
  id: string;
  title: string;
  a1: number;
  d1: number;
  n1: number;
  d2: number;
  n2: number;
  ask: "term" | "sum";
  context: string;
  difficulty: 1 | 2 | 3;
};

function buildTemplate(c: ChangeCase): QuestionTemplate {
  const totalN = c.n1 + c.n2;
  const aChange = c.a1 + (c.n1 - 1) * c.d1;
  const aLast = aChange + c.n2 * c.d2;
  const sum1 = (c.n1 * (c.a1 + aChange)) / 2;
  const sum2 = (c.n2 * (aChange + c.d2 + aLast)) / 2;
  const answer = c.ask === "term" ? aLast : sum1 + sum2;
  const askText = c.ask === "term" ? `${totalN}日目の値を求めよ。` : `${totalN}日間の合計を求めよ。`;
  return {
    meta: {
      id: c.id,
      topicId: c.ask === "term" ? "seq_arithmetic_basic" : "seq_arithmetic_sum_basic",
      title: c.title,
      difficulty: c.difficulty,
      tags: ["sequence", "arithmetic", "ct"],
    },
    generate() {
      return {
        templateId: c.id,
        statement: `${c.context}${askText}`,
        answerKind: "numeric",
        params: {},
      };
    },
    grade(_params, userAnswer) {
      return gradeNumeric(userAnswer, answer);
    },
    explain() {
      return `### この問題の解説\n前半${c.n1}日と後半${c.n2}日で増加量が変わるので分けて計算する。\n答えは **${answer}**。`;
    },
  };
}

const CASES: ChangeCase[] = [
  {
    id: "seq_ct_change_1",
    title: "練習量 変更 1",
    a1: 20,
    d1: 3,
    n1: 5,
    d2: 1,
    n2: 4,
    ask: "term",
    context: "1日目20分から5日間は毎日3分ずつ増やし、その後4日間は毎日1分ずつ増やす。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_2",
    title: "練習量 変更 2",
    a1: 10,
    d1: 2,
    n1: 6,
    d2: -1,
    n2: 4,
    ask: "sum",
    context: "1日目10分から6日間は毎日2分ずつ増やし、その後4日間は毎日1分ずつ減らす。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_3",
    title: "売上 変更 1",
    a1: 80,
    d1: 5,
    n1: 4,
    d2: 2,
    n2: 6,
    ask: "sum",
    context: "1日目80万円から4日間は毎日5万円ずつ増え、その後6日間は毎日2万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_4",
    title: "人数 変更 1",
    a1: 35,
    d1: -1,
    n1: 3,
    d2: -2,
    n2: 5,
    ask: "term",
    context: "初め35人から3年間は毎年1人ずつ減り、その後5年間は毎年2人ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_5",
    title: "積立 変更 1",
    a1: 1000,
    d1: 200,
    n1: 5,
    d2: 100,
    n2: 5,
    ask: "sum",
    context: "初月1000円から5か月は毎月200円ずつ増え、その後5か月は毎月100円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_6",
    title: "練習量 変更 3",
    a1: 30,
    d1: 2,
    n1: 4,
    d2: 5,
    n2: 3,
    ask: "term",
    context: "1日目30分から4日間は毎日2分ずつ増やし、その後3日間は毎日5分ずつ増やす。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_7",
    title: "売上 変更 2",
    a1: 100,
    d1: -5,
    n1: 3,
    d2: -2,
    n2: 5,
    ask: "sum",
    context: "1日目100万円から3日間は毎日5万円ずつ減り、その後5日間は毎日2万円ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_8",
    title: "人数 変更 2",
    a1: 50,
    d1: 4,
    n1: 5,
    d2: -1,
    n2: 4,
    ask: "term",
    context: "初め50人から5回は毎回4人ずつ増え、その後4回は毎回1人ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_9",
    title: "売上 変更 3",
    a1: 70,
    d1: 4,
    n1: 6,
    d2: 2,
    n2: 5,
    ask: "sum",
    context: "1日目70万円から6日間は毎日4万円ずつ増え、その後5日間は毎日2万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_10",
    title: "練習量 変更 4",
    a1: 12,
    d1: 3,
    n1: 4,
    d2: -2,
    n2: 3,
    ask: "term",
    context: "1日目12分から4日間は毎日3分ずつ増やし、その後3日間は毎日2分ずつ減らす。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_11",
    title: "売上 変更 4",
    a1: 60,
    d1: 6,
    n1: 5,
    d2: -3,
    n2: 4,
    ask: "sum",
    context: "1日目60万円から5日間は毎日6万円ずつ増え、その後4日間は毎日3万円ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_12",
    title: "人数 変更 3",
    a1: 20,
    d1: 5,
    n1: 3,
    d2: 1,
    n2: 6,
    ask: "term",
    context: "初め20人から3回は毎回5人ずつ増え、その後6回は毎回1人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_13",
    title: "歩数 変更 1",
    a1: 5000,
    d1: 500,
    n1: 4,
    d2: 200,
    n2: 5,
    ask: "sum",
    context: "1日目5000歩から4日間は毎日500歩ずつ増え、その後5日間は毎日200歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_14",
    title: "売上 変更 5",
    a1: 90,
    d1: 5,
    n1: 4,
    d2: -2,
    n2: 6,
    ask: "sum",
    context: "1日目90万円から4日間は毎日5万円ずつ増え、その後6日間は毎日2万円ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_15",
    title: "練習量 変更 5",
    a1: 18,
    d1: 4,
    n1: 3,
    d2: 1,
    n2: 6,
    ask: "term",
    context: "1日目18分から3日間は毎日4分ずつ増やし、その後6日間は毎日1分ずつ増やす。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_16",
    title: "人数 変更 4",
    a1: 40,
    d1: -2,
    n1: 4,
    d2: -1,
    n2: 5,
    ask: "term",
    context: "初め40人から4回は毎回2人ずつ減り、その後5回は毎回1人ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_17",
    title: "売上 変更 6",
    a1: 100,
    d1: 8,
    n1: 3,
    d2: 3,
    n2: 7,
    ask: "sum",
    context: "1日目100万円から3日間は毎日8万円ずつ増え、その後7日間は毎日3万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_18",
    title: "練習量 変更 6",
    a1: 25,
    d1: 5,
    n1: 4,
    d2: 0,
    n2: 4,
    ask: "term",
    context: "1日目25分から4日間は毎日5分ずつ増やし、その後4日間は同じ時間を続ける。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_19",
    title: "人数 変更 5",
    a1: 30,
    d1: 3,
    n1: 5,
    d2: -2,
    n2: 4,
    ask: "sum",
    context: "初め30人から5回は毎回3人ずつ増え、その後4回は毎回2人ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_20",
    title: "売上 変更 7",
    a1: 80,
    d1: 4,
    n1: 5,
    d2: 0,
    n2: 4,
    ask: "term",
    context: "1日目80万円から5日間は毎日4万円ずつ増え、その後4日間は同じ売上が続く。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_21",
    title: "練習量 変更 7",
    a1: 14,
    d1: 2,
    n1: 6,
    d2: -1,
    n2: 3,
    ask: "sum",
    context: "1日目14分から6日間は毎日2分ずつ増やし、その後3日間は毎日1分ずつ減らす。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_22",
    title: "売上 変更 8",
    a1: 70,
    d1: 5,
    n1: 4,
    d2: 1,
    n2: 6,
    ask: "sum",
    context: "1日目70万円から4日間は毎日5万円ずつ増え、その後6日間は毎日1万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_23",
    title: "人数 変更 6",
    a1: 25,
    d1: -1,
    n1: 5,
    d2: 2,
    n2: 4,
    ask: "term",
    context: "初め25人から5回は毎回1人ずつ減り、その後4回は毎回2人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_24",
    title: "売上 変更 9",
    a1: 85,
    d1: 5,
    n1: 6,
    d2: -2,
    n2: 4,
    ask: "sum",
    context: "1日目85万円から6日間は毎日5万円ずつ増え、その後4日間は毎日2万円ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_25",
    title: "練習量 変更 8",
    a1: 20,
    d1: 3,
    n1: 5,
    d2: 1,
    n2: 5,
    ask: "term",
    context: "1日目20分から5日間は毎日3分ずつ増やし、その後5日間は毎日1分ずつ増やす。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_26",
    title: "人数 変更 7",
    a1: 18,
    d1: 2,
    n1: 4,
    d2: -1,
    n2: 4,
    ask: "sum",
    context: "初め18人から4回は毎回2人ずつ増え、その後4回は毎回1人ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_27",
    title: "売上 変更 10",
    a1: 75,
    d1: -3,
    n1: 4,
    d2: 2,
    n2: 5,
    ask: "term",
    context: "1日目75万円から4日間は毎日3万円ずつ減り、その後5日間は毎日2万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_28",
    title: "歩数 変更 2",
    a1: 5500,
    d1: 400,
    n1: 3,
    d2: 100,
    n2: 6,
    ask: "sum",
    context: "1日目5500歩から3日間は毎日400歩ずつ増え、その後6日間は毎日100歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_29",
    title: "練習量 変更 9",
    a1: 18,
    d1: 2,
    n1: 4,
    d2: 0,
    n2: 5,
    ask: "sum",
    context: "1日目18分から4日間は毎日2分ずつ増やし、その後5日間は同じ時間を続ける。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_30",
    title: "売上 変更 11",
    a1: 60,
    d1: 5,
    n1: 5,
    d2: -1,
    n2: 5,
    ask: "sum",
    context: "1日目60万円から5日間は毎日5万円ずつ増え、その後5日間は毎日1万円ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_31",
    title: "人数 変更 8",
    a1: 22,
    d1: 4,
    n1: 4,
    d2: 0,
    n2: 4,
    ask: "term",
    context: "初め22人から4回は毎回4人ずつ増え、その後4回は同じ人数が続く。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_32",
    title: "売上 変更 12",
    a1: 90,
    d1: 6,
    n1: 4,
    d2: -2,
    n2: 5,
    ask: "sum",
    context: "1日目90万円から4日間は毎日6万円ずつ増え、その後5日間は毎日2万円ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_33",
    title: "練習量 変更 10",
    a1: 15,
    d1: 3,
    n1: 5,
    d2: 0,
    n2: 3,
    ask: "sum",
    context: "1日目15分から5日間は毎日3分ずつ増やし、その後3日間は同じ時間を続ける。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_34",
    title: "売上 変更 13",
    a1: 100,
    d1: 4,
    n1: 4,
    d2: -3,
    n2: 4,
    ask: "sum",
    context: "1日目100万円から4日間は毎日4万円ずつ増え、その後4日間は毎日3万円ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_35",
    title: "人数 変更 9",
    a1: 28,
    d1: -2,
    n1: 3,
    d2: 1,
    n2: 6,
    ask: "term",
    context: "初め28人から3回は毎回2人ずつ減り、その後6回は毎回1人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_36",
    title: "売上 変更 14",
    a1: 95,
    d1: 4,
    n1: 5,
    d2: -1,
    n2: 4,
    ask: "sum",
    context: "1日目95万円から5日間は毎日4万円ずつ増え、その後4日間は毎日1万円ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_37",
    title: "練習量 変更 11",
    a1: 22,
    d1: 2,
    n1: 4,
    d2: 0,
    n2: 4,
    ask: "term",
    context: "1日目22分から4日間は毎日2分ずつ増やし、その後4日間は同じ時間を続ける。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_38",
    title: "売上 変更 15",
    a1: 82,
    d1: 4,
    n1: 5,
    d2: 1,
    n2: 5,
    ask: "sum",
    context: "1日目82万円から5日間は毎日4万円ずつ増え、その後5日間は毎日1万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_39",
    title: "人数 変更 10",
    a1: 26,
    d1: -1,
    n1: 4,
    d2: 2,
    n2: 4,
    ask: "term",
    context: "初め26人から4回は毎回1人ずつ減り、その後4回は毎回2人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_40",
    title: "売上 変更 16",
    a1: 88,
    d1: 6,
    n1: 4,
    d2: -2,
    n2: 5,
    ask: "sum",
    context: "1日目88万円から4日間は毎日6万円ずつ増え、その後5日間は毎日2万円ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_41",
    title: "練習量 変更 12",
    a1: 19,
    d1: 2,
    n1: 5,
    d2: 0,
    n2: 4,
    ask: "sum",
    context: "1日目19分から5日間は毎日2分ずつ増やし、その後4日間は同じ時間を続ける。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_42",
    title: "通学 変更 3",
    a1: 30,
    d1: 2,
    n1: 4,
    d2: -1,
    n2: 5,
    ask: "sum",
    context: "初日30分から4日間は毎日2分ずつ増え、その後5日間は毎日1分ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_43",
    title: "練習 変更 13",
    a1: 12,
    d1: 3,
    n1: 3,
    d2: 1,
    n2: 4,
    ask: "sum",
    context: "初日12分から3日間は毎日3分ずつ増え、その後4日間は毎日1分ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_44",
    title: "配布 変更 5",
    a1: 50,
    d1: -4,
    n1: 4,
    d2: -2,
    n2: 3,
    ask: "sum",
    context: "初回50枚から4回は毎回4枚ずつ減り、その後3回は毎回2枚ずつ減る。",
    difficulty: 3,
  },
  {
    id: "seq_ct_change_45",
    title: "売上 変更 17",
    a1: 70,
    d1: 5,
    n1: 5,
    d2: 0,
    n2: 3,
    ask: "sum",
    context: "1日目70万円から5日間は毎日5万円ずつ増え、その後3日間は同じ売上が続く。",
    difficulty: 2,
  },
  {
    id: "seq_ct_change_46",
    title: "来客 変更 2",
    a1: 40,
    d1: 4,
    n1: 3,
    d2: -3,
    n2: 4,
    ask: "sum",
    context: "初日40人から3日間は毎日4人ずつ増え、その後4日間は毎日3人ずつ減る。",
    difficulty: 3,
  },
];

export const sequenceCtWordChangeTemplates: QuestionTemplate[] = CASES.map(buildTemplate);
