// src/lib/course/templates/mathB/sequence_ct_geometric_limit_word_basic.ts
import type { QuestionTemplate } from "../../types";
import { gradeNumeric } from "../_shared/utils";

type LimitCase = {
  id: string;
  title: string;
  a1?: number;
  r: number;
  ask: "sum" | "a1";
  sum?: number;
  context: string;
  difficulty: 1 | 2 | 3;
};

function buildSumTemplate(c: LimitCase & { a1: number }): QuestionTemplate {
  const sum = c.a1 / (1 - c.r);
  return {
    meta: {
      id: c.id,
      topicId: "seq_geometric_limit_basic",
      title: c.title,
      difficulty: c.difficulty,
      tags: ["sequence", "geometric", "limit", "ct"],
    },
    generate() {
      return {
        templateId: c.id,
        statement: `${c.context}初項 ${c.a1}、公比 ${c.r} の等比数列の無限和 $S$ を求めよ。`,
        answerKind: "numeric",
        params: {},
      };
    },
    grade(_params, userAnswer) {
      return gradeNumeric(userAnswer, sum);
    },
    explain() {
      return `### この問題の解説\n無限和は $S=\\frac{a_1}{1-r}$。\n答えは **${sum}**。`;
    },
  };
}

function buildBacksolveTemplate(c: LimitCase): QuestionTemplate {
  const a1 = (c.sum ?? 0) * (1 - c.r);
  return {
    meta: {
      id: c.id,
      topicId: "seq_geometric_limit_basic",
      title: c.title,
      difficulty: c.difficulty,
      tags: ["sequence", "geometric", "limit", "ct"],
    },
    generate() {
      return {
        templateId: c.id,
        statement: `${c.context}公比 ${c.r} の等比数列の無限和が $S=${c.sum}$ のとき、初項 $a_1$ を求めよ。`,
        answerKind: "numeric",
        params: {},
      };
    },
    grade(_params, userAnswer) {
      return gradeNumeric(userAnswer, a1);
    },
    explain() {
      return `### この問題の解説\n$S=\\frac{a_1}{1-r}$ より $a_1=S(1-r)$。\n答えは **${a1}**。`;
    },
  };
}

const SUM_CASES: Array<LimitCase & { a1: number }> = [
  {
    id: "seq_ct_geo_limit_1",
    title: "無限和 1",
    a1: 4,
    r: 0.5,
    ask: "sum",
    context: "ボールの跳ね返りの高さが毎回1/2になるとき、",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_limit_2",
    title: "無限和 2",
    a1: 10,
    r: 0.2,
    ask: "sum",
    context: "毎回の追加量が前回の1/5になるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_5",
    title: "無限和 3",
    a1: 6,
    r: 0.6,
    ask: "sum",
    context: "作業効率が毎回60%ずつ残るとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_8",
    title: "無限和 4",
    a1: 12,
    r: 0.25,
    ask: "sum",
    context: "支出が毎回1/4ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_9",
    title: "無限和 5",
    a1: 5,
    r: 0.4,
    ask: "sum",
    context: "回収率が毎回40%ずつになるとき、",
    difficulty: 3,
  },
  {
    id: "seq_ct_geo_limit_10",
    title: "無限和 6",
    a1: 8,
    r: 0.75,
    ask: "sum",
    context: "減少率が毎回3/4になるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_11",
    title: "無限和 7",
    a1: 15,
    r: 0.3,
    ask: "sum",
    context: "支出が毎回30%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_12",
    title: "無限和 8",
    a1: 9,
    r: 0.2,
    ask: "sum",
    context: "増分が毎回1/5ずつになるとき、",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_limit_16",
    title: "無限和 9",
    a1: 7,
    r: 0.5,
    ask: "sum",
    context: "支出が毎回半分ずつになるとき、",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_limit_17",
    title: "無限和 10",
    a1: 18,
    r: 0.6,
    ask: "sum",
    context: "回収率が毎回60%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_20",
    title: "無限和 11",
    a1: 3,
    r: 0.75,
    ask: "sum",
    context: "支出が毎回3/4ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_21",
    title: "無限和 12",
    a1: 20,
    r: 0.1,
    ask: "sum",
    context: "増分が毎回1/10ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_24",
    title: "無限和 13",
    a1: 4,
    r: 0.2,
    ask: "sum",
    context: "作業効率が毎回1/5ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_26",
    title: "無限和 14",
    a1: 6,
    r: 0.5,
    ask: "sum",
    context: "支出が毎回1/2ずつになるとき、",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_limit_28",
    title: "無限和 15",
    a1: 10,
    r: 0.4,
    ask: "sum",
    context: "回収率が毎回40%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_30",
    title: "無限和 16",
    a1: 9,
    r: 0.3,
    ask: "sum",
    context: "減少率が毎回30%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_32",
    title: "無限和 17",
    a1: 12,
    r: 0.2,
    ask: "sum",
    context: "回収率が毎回1/5ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_34",
    title: "無限和 18",
    a1: 15,
    r: 0.6,
    ask: "sum",
    context: "減少率が毎回60%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_36",
    title: "無限和 19",
    a1: 8,
    r: 0.25,
    ask: "sum",
    context: "支出が毎回1/4ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_38",
    title: "無限和 20",
    a1: 5,
    r: 0.2,
    ask: "sum",
    context: "回収率が毎回1/5ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_40",
    title: "無限和 21",
    a1: 6,
    r: 0.3,
    ask: "sum",
    context: "回収率が毎回30%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_42",
    title: "無限和 22",
    a1: 18,
    r: 0.75,
    ask: "sum",
    context: "減少率が毎回3/4ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_44",
    title: "無限和 23",
    a1: 7,
    r: 0.2,
    ask: "sum",
    context: "回収率が毎回1/5ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_46",
    title: "無限和 24",
    a1: 20,
    r: 0.5,
    ask: "sum",
    context: "減少率が毎回1/2ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_48",
    title: "無限和 25",
    a1: 9,
    r: 0.25,
    ask: "sum",
    context: "支出が毎回1/4ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_50",
    title: "無限和 26",
    a1: 16,
    r: 0.8,
    ask: "sum",
    context: "回収率が毎回80%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_52",
    title: "無限和 27",
    a1: 12,
    r: 0.6,
    ask: "sum",
    context: "回収率が毎回60%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_54",
    title: "無限和 28",
    a1: 9,
    r: 0.5,
    ask: "sum",
    context: "減少率が毎回1/2ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_56",
    title: "無限和 29",
    a1: 8,
    r: 0.25,
    ask: "sum",
    context: "支出が毎回1/4ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_58",
    title: "無限和 30",
    a1: 10,
    r: 0.5,
    ask: "sum",
    context: "減少率が毎回1/2ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_60",
    title: "無限和 31",
    a1: 8,
    r: 0.2,
    ask: "sum",
    context: "回収率が毎回1/5ずつになるとき、",
    difficulty: 2,
  },
];

const BACKSOLVE_CASES: LimitCase[] = [
  {
    id: "seq_ct_geo_limit_3",
    title: "初項 1",
    r: 0.5,
    ask: "a1",
    sum: 12,
    context: "割引が毎回半分ずつになるとき、",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_limit_4",
    title: "初項 2",
    r: 0.25,
    ask: "a1",
    sum: 20,
    context: "減少率が毎回1/4になるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_6",
    title: "初項 3",
    r: 0.8,
    ask: "a1",
    sum: 50,
    context: "回収量が毎回80%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_7",
    title: "初項 4",
    r: 0.6,
    ask: "a1",
    sum: 30,
    context: "作業効率が毎回60%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_13",
    title: "初項 5",
    r: 0.75,
    ask: "a1",
    sum: 40,
    context: "減少率が毎回3/4になるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_14",
    title: "初項 6",
    r: 0.4,
    ask: "a1",
    sum: 25,
    context: "回収率が毎回40%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_15",
    title: "初項 7",
    r: 0.2,
    ask: "a1",
    sum: 9,
    context: "増分が毎回1/5ずつになるとき、",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_limit_18",
    title: "初項 8",
    r: 0.5,
    ask: "a1",
    sum: 16,
    context: "減少率が毎回1/2になるとき、",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_limit_19",
    title: "初項 9",
    r: 0.25,
    ask: "a1",
    sum: 20,
    context: "支出が毎回1/4ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_22",
    title: "初項 10",
    r: 0.75,
    ask: "a1",
    sum: 12,
    context: "減少率が毎回3/4になるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_23",
    title: "初項 11",
    r: 0.1,
    ask: "a1",
    sum: 30,
    context: "増分が毎回1/10ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_25",
    title: "初項 12",
    r: 0.2,
    ask: "a1",
    sum: 10,
    context: "作業効率が毎回1/5ずつになるとき、",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_limit_27",
    title: "初項 13",
    r: 0.5,
    ask: "a1",
    sum: 14,
    context: "支出が毎回1/2ずつになるとき、",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_limit_29",
    title: "初項 14",
    r: 0.4,
    ask: "a1",
    sum: 25,
    context: "回収率が毎回40%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_31",
    title: "初項 15",
    r: 0.3,
    ask: "a1",
    sum: 12,
    context: "減少率が毎回30%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_33",
    title: "初項 16",
    r: 0.2,
    ask: "a1",
    sum: 18,
    context: "回収率が毎回1/5ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_35",
    title: "初項 17",
    r: 0.6,
    ask: "a1",
    sum: 30,
    context: "減少率が毎回60%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_37",
    title: "初項 18",
    r: 0.25,
    ask: "a1",
    sum: 24,
    context: "支出が毎回1/4ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_39",
    title: "初項 19",
    r: 0.2,
    ask: "a1",
    sum: 20,
    context: "回収率が毎回1/5ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_41",
    title: "初項 20",
    r: 0.3,
    ask: "a1",
    sum: 21,
    context: "回収率が毎回30%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_43",
    title: "初項 21",
    r: 0.75,
    ask: "a1",
    sum: 24,
    context: "減少率が毎回3/4ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_45",
    title: "初項 22",
    r: 0.2,
    ask: "a1",
    sum: 14,
    context: "回収率が毎回1/5ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_47",
    title: "初項 23",
    r: 0.5,
    ask: "a1",
    sum: 30,
    context: "減少率が毎回1/2ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_49",
    title: "初項 24",
    r: 0.25,
    ask: "a1",
    sum: 12,
    context: "支出が毎回1/4ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_51",
    title: "初項 25",
    r: 0.8,
    ask: "a1",
    sum: 40,
    context: "回収率が毎回80%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_53",
    title: "初項 26",
    r: 0.6,
    ask: "a1",
    sum: 30,
    context: "回収率が毎回60%ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_55",
    title: "初項 27",
    r: 0.5,
    ask: "a1",
    sum: 18,
    context: "減少率が毎回1/2ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_57",
    title: "初項 28",
    r: 0.25,
    ask: "a1",
    sum: 16,
    context: "支出が毎回1/4ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_59",
    title: "初項 29",
    r: 0.5,
    ask: "a1",
    sum: 20,
    context: "減少率が毎回1/2ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_61",
    title: "初項 30",
    r: 0.2,
    ask: "a1",
    sum: 24,
    context: "回収率が毎回1/5ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_62",
    title: "無限和 32",
    a1: 18,
    r: 0.5,
    ask: "sum",
    context: "支出が毎回1/2ずつになるとき、",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_limit_63",
    title: "無限和 33",
    a1: 12,
    r: 0.25,
    ask: "sum",
    context: "減衰率が毎回1/4ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_64",
    title: "初項 31",
    r: 0.4,
    ask: "a1",
    sum: 20,
    context: "減少率が毎回2/5ずつになるとき、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_limit_65",
    title: "初項 32",
    r: 0.5,
    ask: "a1",
    sum: 30,
    context: "減少率が毎回1/2ずつになるとき、",
    difficulty: 1,
  },
  {
    id: "seq_ct_geo_limit_66",
    title: "無限和 34",
    a1: 15,
    r: 0.2,
    ask: "sum",
    context: "回収率が毎回1/5ずつになるとき、",
    difficulty: 2,
  },
];

export const sequenceCtGeometricLimitWordTemplates: QuestionTemplate[] = [
  ...SUM_CASES.map(buildSumTemplate),
  ...BACKSOLVE_CASES.map(buildBacksolveTemplate),
];
