// src/lib/course/templates/mathB/sequence_ct_recurrence_word_basic.ts
import type { QuestionTemplate } from "../../types";
import { gradeNumeric } from "../_shared/utils";

type RecWordCase = {
  id: string;
  title: string;
  a1: number;
  d?: number;
  r?: number;
  n: number;
  context: string;
  difficulty: 1 | 2 | 3;
};

function buildArithmeticTemplate(c: RecWordCase): QuestionTemplate {
  const value = c.a1 + (c.n - 1) * (c.d ?? 0);
  return {
    meta: {
      id: c.id,
      topicId: "seq_recurrence_basic",
      title: c.title,
      difficulty: c.difficulty,
      tags: ["sequence", "recurrence", "ct"],
    },
    generate() {
      return {
        templateId: c.id,
        statement: `${c.context}毎回の増加が一定のとき、${c.n}回目の値を求めよ。`,
        answerKind: "numeric",
        params: {},
      };
    },
    grade(_params, userAnswer) {
      return gradeNumeric(userAnswer, value);
    },
    explain() {
      return `### この問題の解説\n等差型の漸化式なので $a_n=a_1+(n-1)d$。\n答えは **${value}**。`;
    },
  };
}

function buildGeometricTemplate(c: RecWordCase): QuestionTemplate {
  const value = c.a1 * Math.pow(c.r ?? 1, c.n - 1);
  return {
    meta: {
      id: c.id,
      topicId: "seq_recurrence_basic",
      title: c.title,
      difficulty: c.difficulty,
      tags: ["sequence", "recurrence", "ct"],
    },
    generate() {
      return {
        templateId: c.id,
        statement: `${c.context}毎回の倍率が一定のとき、${c.n}回目の値を求めよ。`,
        answerKind: "numeric",
        params: {},
      };
    },
    grade(_params, userAnswer) {
      return gradeNumeric(userAnswer, value);
    },
    explain() {
      return `### この問題の解説\n等比型の漸化式なので $a_n=a_1r^{n-1}$。\n答えは **${value}**。`;
    },
  };
}

const ARITH_CASES: RecWordCase[] = [
  {
    id: "seq_ct_recur_word_1",
    title: "積立 1",
    a1: 1000,
    d: 300,
    n: 6,
    context: "貯金額が初回1000円で、以後毎回300円ずつ増える。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_2",
    title: "生産 1",
    a1: 40,
    d: -2,
    n: 8,
    context: "生産数が初日40個で、以後毎日2個ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_3",
    title: "練習 1",
    a1: 15,
    d: 3,
    n: 10,
    context: "練習時間が初日15分で、以後毎日3分ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_4",
    title: "人数 1",
    a1: 28,
    d: -1,
    n: 12,
    context: "人数が初め28人で、以後毎回1人ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_5",
    title: "売上 1",
    a1: 60,
    d: 5,
    n: 9,
    context: "売上が初日60万円で、以後毎日5万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_11",
    title: "通学 1",
    a1: 12,
    d: 4,
    n: 15,
    context: "通学の往復時間が初日12分で、以後毎日4分ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_12",
    title: "在庫 2",
    a1: 50,
    d: -3,
    n: 9,
    context: "在庫数が初日50個で、以後毎日3個ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_13",
    title: "参加者 2",
    a1: 25,
    d: 2,
    n: 11,
    context: "参加者数が初回25人で、以後毎回2人ずつ増える。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_14",
    title: "作業量 2",
    a1: 90,
    d: -5,
    n: 7,
    context: "作業量が初回90で、以後毎回5ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_15",
    title: "気温 1",
    a1: 18,
    d: 1,
    n: 8,
    context: "気温が初日18℃で、以後毎日1℃ずつ上がる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_21",
    title: "交通量 1",
    a1: 120,
    d: 10,
    n: 7,
    context: "交通量が初日120で、以後毎日10ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_22",
    title: "減少 4",
    a1: 75,
    d: -5,
    n: 6,
    context: "量が初め75で、以後毎回5ずつ減る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_23",
    title: "得点 1",
    a1: 12,
    d: 3,
    n: 9,
    context: "得点が初回12点で、以後毎回3点ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_24",
    title: "減少 5",
    a1: 40,
    d: -2,
    n: 10,
    context: "人数が初め40人で、以後毎回2人ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_29",
    title: "増加 7",
    a1: 14,
    d: 2,
    n: 12,
    context: "得点が初回14点で、以後毎回2点ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_30",
    title: "減少 6",
    a1: 90,
    d: -6,
    n: 8,
    context: "量が初め90で、以後毎回6ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_33",
    title: "増加 9",
    a1: 18,
    d: 4,
    n: 10,
    context: "参加者数が初回18人で、以後毎回4人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_34",
    title: "減少 7",
    a1: 55,
    d: -5,
    n: 7,
    context: "在庫が初め55個で、以後毎回5個ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_35",
    title: "増加 10",
    a1: 9,
    d: 3,
    n: 11,
    context: "得点が初回9点で、以後毎回3点ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_39",
    title: "減少 8",
    a1: 72,
    d: -4,
    n: 9,
    context: "量が初め72で、以後毎回4ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_40",
    title: "増加 12",
    a1: 11,
    d: 2,
    n: 13,
    context: "参加者数が初回11人で、以後毎回2人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_43",
    title: "減少 9",
    a1: 64,
    d: -4,
    n: 7,
    context: "量が初め64で、以後毎回4ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_45",
    title: "増加 15",
    a1: 20,
    d: 3,
    n: 9,
    context: "参加者数が初回20人で、以後毎回3人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_47",
    title: "減少 10",
    a1: 80,
    d: -4,
    n: 8,
    context: "量が初め80で、以後毎回4ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_49",
    title: "増加 17",
    a1: 13,
    d: 3,
    n: 10,
    context: "得点が初回13点で、以後毎回3点ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_51",
    title: "減少 11",
    a1: 92,
    d: -6,
    n: 7,
    context: "量が初め92で、以後毎回6ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_53",
    title: "増加 19",
    a1: 16,
    d: 2,
    n: 12,
    context: "参加者数が初回16人で、以後毎回2人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_55",
    title: "減少 12",
    a1: 84,
    d: -7,
    n: 6,
    context: "量が初め84で、以後毎回7ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_57",
    title: "増加 21",
    a1: 10,
    d: 4,
    n: 9,
    context: "参加者数が初回10人で、以後毎回4人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_59",
    title: "減少 13",
    a1: 70,
    d: -5,
    n: 9,
    context: "量が初め70で、以後毎回5ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_61",
    title: "増加 23",
    a1: 14,
    d: 4,
    n: 8,
    context: "参加者数が初回14人で、以後毎回4人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_63",
    title: "減少 14",
    a1: 66,
    d: -3,
    n: 10,
    context: "量が初め66で、以後毎回3ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_65",
    title: "増加 25",
    a1: 15,
    d: 5,
    n: 7,
    context: "参加者数が初回15人で、以後毎回5人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_66",
    title: "減少 15",
    a1: 80,
    d: -5,
    n: 8,
    context: "量が初め80で、以後毎回5ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_69",
    title: "増加 27",
    a1: 12,
    d: 2,
    n: 11,
    context: "参加者数が初回12人で、以後毎回2人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_71",
    title: "減少 16",
    a1: 75,
    d: -5,
    n: 9,
    context: "量が初め75で、以後毎回5ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_73",
    title: "増加 29",
    a1: 18,
    d: 2,
    n: 13,
    context: "参加者数が初回18人で、以後毎回2人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_75",
    title: "減少 17",
    a1: 90,
    d: -5,
    n: 8,
    context: "量が初め90で、以後毎回5ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_77",
    title: "増加 31",
    a1: 16,
    d: 2,
    n: 14,
    context: "参加者数が初回16人で、以後毎回2人ずつ増える。",
    difficulty: 2,
  },
];

const GEO_CASES: RecWordCase[] = [
  {
    id: "seq_ct_recur_word_6",
    title: "菌 1",
    a1: 3,
    r: 2,
    n: 6,
    context: "菌の数が初め3個で、以後毎回2倍になる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_7",
    title: "減衰 1",
    a1: 200,
    r: 0.8,
    n: 5,
    context: "物質量が初め200で、以後毎回80%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_8",
    title: "複利 1",
    a1: 100,
    r: 1.05,
    n: 4,
    context: "資産が初め100万円で、以後毎年5%ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_9",
    title: "減少 1",
    a1: 80,
    r: 0.75,
    n: 6,
    context: "在庫が初め80個で、以後毎回75%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_10",
    title: "増加 1",
    a1: 4,
    r: 3,
    n: 5,
    context: "細胞数が初め4個で、以後毎回3倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_16",
    title: "増加 2",
    a1: 8,
    r: 2,
    n: 6,
    context: "生物数が初め8で、以後毎回2倍になる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_17",
    title: "減少 2",
    a1: 64,
    r: 0.5,
    n: 4,
    context: "量が初め64で、以後毎回半分ずつになる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_18",
    title: "増加 3",
    a1: 3,
    r: 3,
    n: 4,
    context: "菌の数が初め3個で、以後毎回3倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_19",
    title: "減少 3",
    a1: 120,
    r: 0.75,
    n: 4,
    context: "在庫が初め120個で、以後毎回75%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_20",
    title: "増加 4",
    a1: 10,
    r: 2,
    n: 5,
    context: "数が初め10で、以後毎回2倍になる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_25",
    title: "減衰 4",
    a1: 81,
    r: 1 / 3,
    n: 5,
    context: "量が初め81で、以後毎回1/3ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_26",
    title: "増加 5",
    a1: 6,
    r: 2,
    n: 6,
    context: "細胞数が初め6個で、以後毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_27",
    title: "減衰 5",
    a1: 500,
    r: 0.9,
    n: 4,
    context: "在庫が初め500個で、以後毎回90%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_28",
    title: "増加 6",
    a1: 5,
    r: 3,
    n: 4,
    context: "菌の数が初め5個で、以後毎回3倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_31",
    title: "減衰 6",
    a1: 200,
    r: 0.8,
    n: 5,
    context: "量が初め200で、以後毎回80%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_32",
    title: "増加 8",
    a1: 2,
    r: 4,
    n: 4,
    context: "数が初め2で、以後毎回4倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_36",
    title: "減衰 7",
    a1: 160,
    r: 0.5,
    n: 5,
    context: "量が初め160で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_37",
    title: "増加 11",
    a1: 7,
    r: 2,
    n: 6,
    context: "菌の数が初め7個で、以後毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_38",
    title: "減衰 8",
    a1: 300,
    r: 0.8,
    n: 4,
    context: "在庫が初め300個で、以後毎回80%ずつ残る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_41",
    title: "増加 13",
    a1: 3,
    r: 2,
    n: 7,
    context: "数が初め3で、以後毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_42",
    title: "減衰 9",
    a1: 96,
    r: 0.5,
    n: 6,
    context: "量が初め96で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_44",
    title: "増加 14",
    a1: 12,
    r: 2,
    n: 5,
    context: "数が初め12で、以後毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_46",
    title: "減衰 10",
    a1: 128,
    r: 0.5,
    n: 6,
    context: "量が初め128で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_48",
    title: "増加 16",
    a1: 9,
    r: 2,
    n: 6,
    context: "数が初め9で、以後毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_50",
    title: "減衰 11",
    a1: 144,
    r: 0.5,
    n: 5,
    context: "量が初め144で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_52",
    title: "増加 18",
    a1: 8,
    r: 2,
    n: 7,
    context: "数が初め8で、以後毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_54",
    title: "減衰 12",
    a1: 256,
    r: 0.5,
    n: 5,
    context: "量が初め256で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_56",
    title: "増加 20",
    a1: 6,
    r: 2,
    n: 7,
    context: "数が初め6で、以後毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_58",
    title: "減衰 13",
    a1: 200,
    r: 0.5,
    n: 6,
    context: "量が初め200で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_60",
    title: "増加 22",
    a1: 5,
    r: 3,
    n: 5,
    context: "数が初め5で、以後毎回3倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_62",
    title: "減衰 14",
    a1: 180,
    r: 0.5,
    n: 6,
    context: "量が初め180で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_64",
    title: "増加 24",
    a1: 9,
    r: 2,
    n: 8,
    context: "数が初め9で、以後毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_67",
    title: "減衰 15",
    a1: 320,
    r: 0.5,
    n: 6,
    context: "量が初め320で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_68",
    title: "増加 26",
    a1: 4,
    r: 3,
    n: 5,
    context: "数が初め4で、以後毎回3倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_70",
    title: "減衰 16",
    a1: 240,
    r: 0.5,
    n: 6,
    context: "量が初め240で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_72",
    title: "増加 28",
    a1: 7,
    r: 2,
    n: 8,
    context: "数が初め7で、以後毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_74",
    title: "減衰 17",
    a1: 256,
    r: 0.5,
    n: 7,
    context: "量が初め256で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_76",
    title: "増加 30",
    a1: 6,
    r: 2,
    n: 9,
    context: "数が初め6で、以後毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_78",
    title: "減衰 18",
    a1: 300,
    r: 0.5,
    n: 7,
    context: "量が初め300で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_80",
    title: "増加 31",
    a1: 9,
    r: 2,
    n: 8,
    context: "数が初め9で、以後毎回2倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_82",
    title: "減衰 19",
    a1: 512,
    r: 0.5,
    n: 8,
    context: "量が初め512で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_84",
    title: "増加 32",
    a1: 5,
    r: 3,
    n: 6,
    context: "数が初め5で、以後毎回3倍になる。",
    difficulty: 2,
  },
  {
    id: "seq_ct_recur_word_86",
    title: "減衰 20",
    a1: 900,
    r: 0.5,
    n: 6,
    context: "量が初め900で、以後毎回半分ずつ残る。",
    difficulty: 1,
  },
  {
    id: "seq_ct_recur_word_88",
    title: "増加 33",
    a1: 4,
    r: 2,
    n: 10,
    context: "数が初め4で、以後毎回2倍になる。",
    difficulty: 2,
  },
];

export const sequenceCtRecurrenceWordTemplates: QuestionTemplate[] = [
  ...ARITH_CASES.map(buildArithmeticTemplate),
  ...GEO_CASES.map(buildGeometricTemplate),
];
