// src/lib/course/templates/mathB/sequence_ct_word_basic.ts
import type { QuestionTemplate } from "../../types";
import { gradeNumeric } from "../_shared/utils";

type WordCase = {
  id: string;
  title: string;
  a1: number;
  d: number;
  n: number;
  ask: "sum" | "term";
  context: string;
  difficulty: 1 | 2 | 3;
};

function buildTemplate(c: WordCase): QuestionTemplate {
  const an = c.a1 + (c.n - 1) * c.d;
  const sum = (c.n * (c.a1 + an)) / 2;
  const answer = c.ask === "sum" ? sum : an;
  const suffix =
    c.ask === "sum" ? `${c.n}回（または${c.n}日間）の合計を求めよ。` : `${c.n}回目（または${c.n}日目）を求めよ。`;
  return {
    meta: {
      id: c.id,
      topicId: c.ask === "sum" ? "seq_arithmetic_sum_basic" : "seq_arithmetic_basic",
      title: c.title,
      difficulty: c.difficulty,
      tags: ["sequence", "arithmetic", "ct"],
    },
    generate() {
      return {
        templateId: c.id,
        statement: `${c.context}${suffix}`,
        answerKind: "numeric",
        params: {},
      };
    },
    grade(_params, userAnswer) {
      return gradeNumeric(userAnswer, answer);
    },
    explain() {
      return `### この問題の解説\n等差数列で $a_1=${c.a1},\\ d=${c.d}$。\n${c.ask === "sum" ? `和は $S_n=\\frac{n}{2}(a_1+a_n)$。` : `一般項は $a_n=a_1+(n-1)d$。`}\n答えは **${answer}**。`;
    },
  };
}

const CASES: WordCase[] = [
  {
    id: "seq_ct_word_1",
    title: "積立金 1",
    a1: 2000,
    d: 500,
    n: 6,
    ask: "sum",
    context: "毎月の積立額が初月2000円で、以後毎月500円ずつ増えるとする。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_2",
    title: "階段 1",
    a1: 3,
    d: 2,
    n: 10,
    ask: "term",
    context: "階段の1段目が3cmで、以後2cmずつ高くなる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_3",
    title: "ポイント 1",
    a1: 120,
    d: 30,
    n: 8,
    ask: "sum",
    context: "毎週の獲得ポイントが初週120点で、以後毎週30点ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_4",
    title: "練習量 1",
    a1: 15,
    d: 5,
    n: 7,
    ask: "sum",
    context: "1日目の練習量が15分で、毎日5分ずつ増やす。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_5",
    title: "生産数 1",
    a1: 28,
    d: -2,
    n: 9,
    ask: "term",
    context: "工場の1日目の生産数が28個で、以後毎日2個ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_6",
    title: "歩数 1",
    a1: 6500,
    d: 400,
    n: 5,
    ask: "sum",
    context: "1日目の歩数が6500歩で、以後毎日400歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_7",
    title: "座席数 1",
    a1: 40,
    d: 3,
    n: 12,
    ask: "term",
    context: "段ごとの座席数が初段40席で、以後3席ずつ増える。",
    difficulty: 3,
  },
  {
    id: "seq_ct_word_8",
    title: "練習量 2",
    a1: 20,
    d: -1,
    n: 10,
    ask: "sum",
    context: "1日目の練習量が20分で、以後毎日1分ずつ減らす。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_9",
    title: "収益 1",
    a1: 80,
    d: 5,
    n: 9,
    ask: "sum",
    context: "1日目の収益が80万円で、以後毎日5万円ずつ増える。",
    difficulty: 3,
  },
  {
    id: "seq_ct_word_10",
    title: "生徒数 1",
    a1: 32,
    d: -1,
    n: 6,
    ask: "term",
    context: "クラスの人数が初め32人で、以後毎年1人ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_11",
    title: "売上 1",
    a1: 150,
    d: 10,
    n: 6,
    ask: "sum",
    context: "1日目の売上が150万円で、以後毎日10万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_12",
    title: "高さ 1",
    a1: 12,
    d: 3,
    n: 8,
    ask: "term",
    context: "積み重ねる箱の高さが初め12cmで、以後3cmずつ高くなる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_13",
    title: "料金 1",
    a1: 900,
    d: 150,
    n: 5,
    ask: "sum",
    context: "料金が初回900円で、以後150円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_14",
    title: "欠席者 1",
    a1: 8,
    d: -1,
    n: 7,
    ask: "sum",
    context: "欠席者数が初日8人で、以後毎日1人ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_15",
    title: "運動時間 1",
    a1: 30,
    d: 2,
    n: 12,
    ask: "term",
    context: "1日目の運動時間が30分で、以後毎日2分ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_16",
    title: "積立金 2",
    a1: 1000,
    d: 200,
    n: 10,
    ask: "sum",
    context: "毎月の積立額が初月1000円で、以後毎月200円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_17",
    title: "階段 2",
    a1: 5,
    d: 3,
    n: 9,
    ask: "term",
    context: "階段の1段目が5cmで、以後3cmずつ高くなる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_18",
    title: "売上 2",
    a1: 120,
    d: 15,
    n: 8,
    ask: "sum",
    context: "1日目の売上が120万円で、以後毎日15万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_19",
    title: "練習量 3",
    a1: 25,
    d: 2,
    n: 14,
    ask: "term",
    context: "1日目の練習量が25分で、以後毎日2分ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_20",
    title: "減少 1",
    a1: 50,
    d: -4,
    n: 6,
    ask: "term",
    context: "作業量が初回50で、以後毎回4ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_21",
    title: "来客 1",
    a1: 200,
    d: 20,
    n: 7,
    ask: "sum",
    context: "1日目の来客数が200人で、以後毎日20人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_22",
    title: "料金 2",
    a1: 500,
    d: 50,
    n: 10,
    ask: "sum",
    context: "料金が初回500円で、以後50円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_23",
    title: "歩数 2",
    a1: 7000,
    d: 300,
    n: 7,
    ask: "sum",
    context: "1日目の歩数が7000歩で、以後毎日300歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_24",
    title: "温度 1",
    a1: 22,
    d: -1,
    n: 9,
    ask: "term",
    context: "気温が初日22℃で、以後毎日1℃ずつ下がる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_25",
    title: "座席 2",
    a1: 30,
    d: 4,
    n: 11,
    ask: "term",
    context: "段ごとの座席数が初段30席で、以後4席ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_26",
    title: "売上 3",
    a1: 90,
    d: 6,
    n: 8,
    ask: "sum",
    context: "1日目の売上が90万円で、以後毎日6万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_27",
    title: "減少 2",
    a1: 60,
    d: -3,
    n: 10,
    ask: "sum",
    context: "初回60で、以後毎回3ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_28",
    title: "来客 2",
    a1: 150,
    d: 10,
    n: 6,
    ask: "term",
    context: "1日目の来客数が150人で、以後毎日10人ずつ増える。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_29",
    title: "売上 4",
    a1: 110,
    d: 5,
    n: 12,
    ask: "sum",
    context: "1日目の売上が110万円で、以後毎日5万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_30",
    title: "減少 3",
    a1: 45,
    d: -2,
    n: 9,
    ask: "term",
    context: "作業量が初回45で、以後毎回2ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_31",
    title: "生産 2",
    a1: 35,
    d: 4,
    n: 8,
    ask: "term",
    context: "1日目の生産数が35個で、以後毎日4個ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_32",
    title: "積立金 3",
    a1: 800,
    d: 100,
    n: 12,
    ask: "sum",
    context: "毎月の積立額が初月800円で、以後毎月100円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_33",
    title: "運動量 1",
    a1: 24,
    d: 2,
    n: 10,
    ask: "sum",
    context: "1日目の運動量が24分で、以後毎日2分ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_34",
    title: "料金 3",
    a1: 400,
    d: 40,
    n: 9,
    ask: "sum",
    context: "料金が初回400円で、以後40円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_35",
    title: "階段 3",
    a1: 6,
    d: 2,
    n: 12,
    ask: "term",
    context: "階段の1段目が6cmで、以後2cmずつ高くなる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_36",
    title: "練習量 4",
    a1: 16,
    d: 4,
    n: 8,
    ask: "sum",
    context: "1日目の練習量が16分で、以後毎日4分ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_37",
    title: "座席 3",
    a1: 26,
    d: 3,
    n: 9,
    ask: "term",
    context: "段ごとの座席数が初段26席で、以後3席ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_38",
    title: "歩数 3",
    a1: 6000,
    d: 500,
    n: 6,
    ask: "sum",
    context: "1日目の歩数が6000歩で、以後毎日500歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_39",
    title: "売上 5",
    a1: 95,
    d: 5,
    n: 10,
    ask: "sum",
    context: "1日目の売上が95万円で、以後毎日5万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_40",
    title: "減少 4",
    a1: 70,
    d: -5,
    n: 7,
    ask: "term",
    context: "作業量が初回70で、以後毎回5ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_41",
    title: "座席 4",
    a1: 28,
    d: 2,
    n: 10,
    ask: "term",
    context: "段ごとの座席数が初段28席で、以後2席ずつ増える。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_42",
    title: "売上 6",
    a1: 105,
    d: 7,
    n: 9,
    ask: "sum",
    context: "1日目の売上が105万円で、以後毎日7万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_43",
    title: "階段 4",
    a1: 4,
    d: 4,
    n: 8,
    ask: "term",
    context: "階段の1段目が4cmで、以後4cmずつ高くなる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_44",
    title: "売上 7",
    a1: 88,
    d: 4,
    n: 11,
    ask: "sum",
    context: "1日目の売上が88万円で、以後毎日4万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_45",
    title: "減少 5",
    a1: 65,
    d: -5,
    n: 8,
    ask: "sum",
    context: "初回65で、以後毎回5ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_46",
    title: "階段 5",
    a1: 7,
    d: 3,
    n: 9,
    ask: "term",
    context: "階段の1段目が7cmで、以後3cmずつ高くなる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_47",
    title: "減少 6",
    a1: 50,
    d: -4,
    n: 9,
    ask: "sum",
    context: "初回50で、以後毎回4ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_48",
    title: "歩数 4",
    a1: 7200,
    d: 300,
    n: 8,
    ask: "term",
    context: "1日目の歩数が7200歩で、以後毎日300歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_49",
    title: "売上 8",
    a1: 92,
    d: 6,
    n: 8,
    ask: "sum",
    context: "1日目の売上が92万円で、以後毎日6万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_50",
    title: "減少 7",
    a1: 58,
    d: -3,
    n: 9,
    ask: "term",
    context: "作業量が初回58で、以後毎回3ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_51",
    title: "座席 5",
    a1: 24,
    d: 4,
    n: 8,
    ask: "term",
    context: "段ごとの座席数が初段24席で、以後4席ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_52",
    title: "売上 9",
    a1: 100,
    d: 5,
    n: 10,
    ask: "sum",
    context: "1日目の売上が100万円で、以後毎日5万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_53",
    title: "減少 8",
    a1: 75,
    d: -5,
    n: 8,
    ask: "term",
    context: "作業量が初回75で、以後毎回5ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_54",
    title: "歩数 5",
    a1: 6800,
    d: 200,
    n: 9,
    ask: "sum",
    context: "1日目の歩数が6800歩で、以後毎日200歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_55",
    title: "売上 10",
    a1: 98,
    d: 2,
    n: 12,
    ask: "sum",
    context: "1日目の売上が98万円で、以後毎日2万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_56",
    title: "減少 9",
    a1: 62,
    d: -2,
    n: 11,
    ask: "term",
    context: "作業量が初回62で、以後毎回2ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_57",
    title: "階段 6",
    a1: 5,
    d: 5,
    n: 7,
    ask: "term",
    context: "階段の1段目が5cmで、以後5cmずつ高くなる。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_58",
    title: "売上 11",
    a1: 90,
    d: 6,
    n: 10,
    ask: "sum",
    context: "1日目の売上が90万円で、以後毎日6万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_59",
    title: "減少 10",
    a1: 68,
    d: -4,
    n: 8,
    ask: "term",
    context: "作業量が初回68で、以後毎回4ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_60",
    title: "歩数 6",
    a1: 6400,
    d: 400,
    n: 7,
    ask: "sum",
    context: "1日目の歩数が6400歩で、以後毎日400歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_61",
    title: "座席 6",
    a1: 32,
    d: 2,
    n: 12,
    ask: "term",
    context: "段ごとの座席数が初段32席で、以後2席ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_62",
    title: "売上 12",
    a1: 104,
    d: 4,
    n: 12,
    ask: "sum",
    context: "1日目の売上が104万円で、以後毎日4万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_63",
    title: "減少 11",
    a1: 72,
    d: -4,
    n: 9,
    ask: "term",
    context: "作業量が初回72で、以後毎回4ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_64",
    title: "歩数 7",
    a1: 7000,
    d: 300,
    n: 10,
    ask: "sum",
    context: "1日目の歩数が7000歩で、以後毎日300歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_65",
    title: "座席 7",
    a1: 36,
    d: 2,
    n: 9,
    ask: "term",
    context: "段ごとの座席数が初段36席で、以後2席ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_66",
    title: "売上 13",
    a1: 110,
    d: 5,
    n: 8,
    ask: "sum",
    context: "1日目の売上が110万円で、以後毎日5万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_67",
    title: "減少 12",
    a1: 78,
    d: -3,
    n: 10,
    ask: "term",
    context: "作業量が初回78で、以後毎回3ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_68",
    title: "歩数 8",
    a1: 6600,
    d: 200,
    n: 10,
    ask: "sum",
    context: "1日目の歩数が6600歩で、以後毎日200歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_69",
    title: "座席 8",
    a1: 30,
    d: 3,
    n: 10,
    ask: "term",
    context: "段ごとの座席数が初段30席で、以後3席ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_70",
    title: "売上 14",
    a1: 102,
    d: 3,
    n: 12,
    ask: "sum",
    context: "1日目の売上が102万円で、以後毎日3万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_71",
    title: "減少 13",
    a1: 74,
    d: -2,
    n: 12,
    ask: "term",
    context: "作業量が初回74で、以後毎回2ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_72",
    title: "歩数 9",
    a1: 6200,
    d: 300,
    n: 9,
    ask: "sum",
    context: "1日目の歩数が6200歩で、以後毎日300歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_73",
    title: "座席 9",
    a1: 34,
    d: 2,
    n: 11,
    ask: "term",
    context: "段ごとの座席数が初段34席で、以後2席ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_74",
    title: "減少 14",
    a1: 76,
    d: -3,
    n: 11,
    ask: "term",
    context: "作業量が初回76で、以後毎回3ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_75",
    title: "歩数 10",
    a1: 6400,
    d: 200,
    n: 11,
    ask: "sum",
    context: "1日目の歩数が6400歩で、以後毎日200歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_76",
    title: "売上 15",
    a1: 96,
    d: 4,
    n: 11,
    ask: "sum",
    context: "1日目の売上が96万円で、以後毎日4万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_77",
    title: "減少 15",
    a1: 70,
    d: -2,
    n: 12,
    ask: "term",
    context: "作業量が初回70で、以後毎回2ずつ減少する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_78",
    title: "歩数 11",
    a1: 6600,
    d: 300,
    n: 9,
    ask: "sum",
    context: "1日目の歩数が6600歩で、以後毎日300歩ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_79",
    title: "座席 10",
    a1: 38,
    d: 2,
    n: 10,
    ask: "term",
    context: "段ごとの座席数が初段38席で、以後2席ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_80",
    title: "売上 16",
    a1: 106,
    d: 4,
    n: 10,
    ask: "sum",
    context: "1日目の売上が106万円で、以後毎日4万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_81",
    title: "来客 12",
    a1: 42,
    d: 3,
    n: 8,
    ask: "term",
    context: "初日の来客数が42人で、以後毎日3人ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_82",
    title: "貯金 9",
    a1: 3000,
    d: 500,
    n: 10,
    ask: "sum",
    context: "1日目に3000円、以後毎日500円ずつ多く貯める。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_83",
    title: "生産 7",
    a1: 120,
    d: -5,
    n: 6,
    ask: "term",
    context: "初回の生産量が120個で、以後毎回5個ずつ減る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_84",
    title: "席数 11",
    a1: 24,
    d: 4,
    n: 7,
    ask: "sum",
    context: "初段が24席で、以後段ごとに4席ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_85",
    title: "距離 6",
    a1: 3,
    d: 1,
    n: 12,
    ask: "sum",
    context: "1周目3kmで、以後1kmずつ増やして走る。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_86",
    title: "単語 5",
    a1: 18,
    d: 2,
    n: 9,
    ask: "term",
    context: "初日の単語数が18語で、以後毎日2語ずつ増える。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_87",
    title: "印刷 4",
    a1: 210,
    d: -10,
    n: 5,
    ask: "sum",
    context: "初回210枚で、以後10枚ずつ減らして印刷する。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_88",
    title: "練習 13",
    a1: 15,
    d: 3,
    n: 6,
    ask: "sum",
    context: "初日15分で、以後毎日3分ずつ増やす。",
    difficulty: 1,
  },
  {
    id: "seq_ct_word_89",
    title: "売上 17",
    a1: 80,
    d: 6,
    n: 8,
    ask: "term",
    context: "初日の売上が80万円で、以後毎日6万円ずつ増える。",
    difficulty: 2,
  },
  {
    id: "seq_ct_word_90",
    title: "点数 8",
    a1: 55,
    d: 5,
    n: 9,
    ask: "sum",
    context: "1回目55点で、以後毎回5点ずつ上がる。",
    difficulty: 2,
  },
];

export const sequenceCtWordTemplates: QuestionTemplate[] = CASES.map(buildTemplate);
