// src/lib/course/templates/mathB/sequence_ct_geometric_change_basic.ts
import type { QuestionTemplate } from "../../types";
import { gradeNumeric } from "../_shared/utils";

type GeoChangeCase = {
  id: string;
  title: string;
  a1: number;
  r1: number;
  n1: number;
  r2: number;
  n2: number;
  ask: "term";
  context: string;
  difficulty: 1 | 2 | 3;
};

function buildTemplate(c: GeoChangeCase): QuestionTemplate {
  const mid = c.a1 * Math.pow(c.r1, c.n1 - 1);
  const last = mid * Math.pow(c.r2, c.n2);
  const answer = Math.round(last * 1000) / 1000;
  const totalN = c.n1 + c.n2;
  return {
    meta: {
      id: c.id,
      topicId: "seq_geometric_basic",
      title: c.title,
      difficulty: c.difficulty,
      tags: ["sequence", "geometric", "ct"],
    },
    generate() {
      return {
        templateId: c.id,
        statement: `${c.context}最初の${c.n1}回は公比 ${c.r1}、その後${c.n2}回は公比 ${c.r2} で増えるとき、${totalN}回目の値を求めよ。`,
        answerKind: "numeric",
        params: {},
      };
    },
    grade(_params, userAnswer) {
      return gradeNumeric(userAnswer, answer);
    },
    explain() {
      return `### この問題の解説\n前半で $a_{${c.n1}}=${mid}$、後半は公比 ${c.r2} で ${c.n2} 回進む。\n答えは **${answer}**。`;
    },
  };
}

const CASES: GeoChangeCase[] = [
  {
    id: "seq_ct_geo_change_1",
    title: "倍率変更 1",
    a1: 2,
    r1: 2,
    n1: 3,
    r2: 1.5,
    n2: 2,
    ask: "term",
    context: "細胞数が初め2個で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_2",
    title: "倍率変更 2",
    a1: 5,
    r1: 3,
    n1: 2,
    r2: 0.5,
    n2: 3,
    ask: "term",
    context: "数量が初め5で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_3",
    title: "倍率変更 3",
    a1: 100,
    r1: 1.1,
    n1: 2,
    r2: 1.05,
    n2: 3,
    ask: "term",
    context: "投資額が初め100万円で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_4",
    title: "倍率変更 4",
    a1: 4,
    r1: 2,
    n1: 4,
    r2: 0.5,
    n2: 2,
    ask: "term",
    context: "細胞数が初め4個で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_5",
    title: "倍率変更 5",
    a1: 9,
    r1: 3,
    n1: 2,
    r2: 2,
    n2: 3,
    ask: "term",
    context: "数量が初め9で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_6",
    title: "倍率変更 6",
    a1: 81,
    r1: 1 / 3,
    n1: 3,
    r2: 2,
    n2: 2,
    ask: "term",
    context: "値が初め81で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_7",
    title: "倍率変更 7",
    a1: 6,
    r1: 2,
    n1: 2,
    r2: 0.5,
    n2: 4,
    ask: "term",
    context: "量が初め6で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_8",
    title: "倍率変更 8",
    a1: 9,
    r1: 1.5,
    n1: 3,
    r2: 2,
    n2: 2,
    ask: "term",
    context: "数が初め9で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_9",
    title: "倍率変更 9",
    a1: 12,
    r1: 2,
    n1: 3,
    r2: 0.75,
    n2: 2,
    ask: "term",
    context: "量が初め12で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_10",
    title: "倍率変更 10",
    a1: 20,
    r1: 1.2,
    n1: 4,
    r2: 0.5,
    n2: 3,
    ask: "term",
    context: "数量が初め20で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_11",
    title: "倍率変更 11",
    a1: 16,
    r1: 2,
    n1: 3,
    r2: 0.25,
    n2: 2,
    ask: "term",
    context: "量が初め16で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_12",
    title: "倍率変更 12",
    a1: 9,
    r1: 3,
    n1: 2,
    r2: 0.5,
    n2: 4,
    ask: "term",
    context: "数が初め9で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_13",
    title: "倍率変更 13",
    a1: 5,
    r1: 2,
    n1: 2,
    r2: 0.8,
    n2: 4,
    ask: "term",
    context: "量が初め5で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_14",
    title: "倍率変更 14",
    a1: 12,
    r1: 1.5,
    n1: 3,
    r2: 2,
    n2: 2,
    ask: "term",
    context: "数が初め12で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_15",
    title: "倍率変更 15",
    a1: 8,
    r1: 2,
    n1: 3,
    r2: 0.5,
    n2: 3,
    ask: "term",
    context: "量が初め8で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_16",
    title: "倍率変更 16",
    a1: 5,
    r1: 3,
    n1: 2,
    r2: 1.2,
    n2: 3,
    ask: "term",
    context: "数が初め5で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_17",
    title: "倍率変更 17",
    a1: 10,
    r1: 2,
    n1: 2,
    r2: 1.5,
    n2: 3,
    ask: "term",
    context: "量が初め10で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_18",
    title: "倍率変更 18",
    a1: 18,
    r1: 0.5,
    n1: 3,
    r2: 2,
    n2: 2,
    ask: "term",
    context: "数が初め18で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_19",
    title: "倍率変更 19",
    a1: 24,
    r1: 2,
    n1: 2,
    r2: 0.75,
    n2: 3,
    ask: "term",
    context: "量が初め24で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_20",
    title: "倍率変更 20",
    a1: 6,
    r1: 3,
    n1: 2,
    r2: 0.5,
    n2: 5,
    ask: "term",
    context: "数が初め6で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_21",
    title: "倍率変更 21",
    a1: 15,
    r1: 2,
    n1: 2,
    r2: 0.8,
    n2: 3,
    ask: "term",
    context: "量が初め15で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_22",
    title: "倍率変更 22",
    a1: 9,
    r1: 0.5,
    n1: 3,
    r2: 2,
    n2: 3,
    ask: "term",
    context: "数が初め9で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_23",
    title: "倍率変更 23",
    a1: 12,
    r1: 2,
    n1: 2,
    r2: 1.5,
    n2: 3,
    ask: "term",
    context: "量が初め12で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_24",
    title: "倍率変更 24",
    a1: 6,
    r1: 3,
    n1: 2,
    r2: 0.8,
    n2: 4,
    ask: "term",
    context: "数が初め6で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_25",
    title: "倍率変更 25",
    a1: 20,
    r1: 2,
    n1: 2,
    r2: 0.9,
    n2: 4,
    ask: "term",
    context: "量が初め20で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_26",
    title: "倍率変更 26",
    a1: 18,
    r1: 0.5,
    n1: 4,
    r2: 2,
    n2: 2,
    ask: "term",
    context: "数が初め18で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_27",
    title: "倍率変更 27",
    a1: 14,
    r1: 2,
    n1: 2,
    r2: 0.75,
    n2: 4,
    ask: "term",
    context: "量が初め14で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_28",
    title: "倍率変更 28",
    a1: 10,
    r1: 1.5,
    n1: 3,
    r2: 0.5,
    n2: 3,
    ask: "term",
    context: "数が初め10で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_29",
    title: "倍率変更 29",
    a1: 12,
    r1: 2,
    n1: 2,
    r2: 0.7,
    n2: 4,
    ask: "term",
    context: "量が初め12で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_30",
    title: "倍率変更 30",
    a1: 15,
    r1: 0.5,
    n1: 3,
    r2: 2,
    n2: 3,
    ask: "term",
    context: "数が初め15で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_31",
    title: "倍率変更 31",
    a1: 8,
    r1: 2,
    n1: 2,
    r2: 0.8,
    n2: 4,
    ask: "term",
    context: "量が初め8で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_32",
    title: "倍率変更 32",
    a1: 12,
    r1: 0.5,
    n1: 4,
    r2: 2,
    n2: 2,
    ask: "term",
    context: "数が初め12で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_33",
    title: "倍率変更 33",
    a1: 18,
    r1: 2,
    n1: 2,
    r2: 0.9,
    n2: 4,
    ask: "term",
    context: "量が初め18で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_34",
    title: "倍率変更 34",
    a1: 9,
    r1: 3,
    n1: 2,
    r2: 0.75,
    n2: 3,
    ask: "term",
    context: "数が初め9で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_35",
    title: "倍率変更 35",
    a1: 16,
    r1: 2,
    n1: 2,
    r2: 0.8,
    n2: 4,
    ask: "term",
    context: "量が初め16で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_36",
    title: "倍率変更 36",
    a1: 12,
    r1: 0.5,
    n1: 3,
    r2: 2,
    n2: 3,
    ask: "term",
    context: "数が初め12で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_37",
    title: "倍率変更 37",
    a1: 20,
    r1: 2,
    n1: 2,
    r2: 0.85,
    n2: 4,
    ask: "term",
    context: "量が初め20で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_38",
    title: "倍率変更 38",
    a1: 9,
    r1: 0.5,
    n1: 4,
    r2: 2,
    n2: 2,
    ask: "term",
    context: "数が初め9で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_39",
    title: "倍率変更 39",
    a1: 16,
    r1: 2,
    n1: 2,
    r2: 0.75,
    n2: 4,
    ask: "term",
    context: "量が初め16で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_40",
    title: "倍率変更 40",
    a1: 8,
    r1: 0.5,
    n1: 4,
    r2: 2,
    n2: 2,
    ask: "term",
    context: "数が初め8で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_41",
    title: "倍率変更 41",
    a1: 18,
    r1: 2,
    n1: 2,
    r2: 0.8,
    n2: 4,
    ask: "term",
    context: "量が初め18で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_42",
    title: "倍率変更 42",
    a1: 10,
    r1: 0.5,
    n1: 4,
    r2: 2,
    n2: 3,
    ask: "term",
    context: "数が初め10で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_43",
    title: "倍率変更 43",
    a1: 14,
    r1: 2,
    n1: 2,
    r2: 0.85,
    n2: 4,
    ask: "term",
    context: "量が初め14で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_44",
    title: "倍率変更 44",
    a1: 12,
    r1: 0.5,
    n1: 5,
    r2: 2,
    n2: 2,
    ask: "term",
    context: "数が初め12で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_45",
    title: "倍率変更 45",
    a1: 14,
    r1: 2,
    n1: 2,
    r2: 0.8,
    n2: 5,
    ask: "term",
    context: "量が初め14で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_46",
    title: "倍率変更 46",
    a1: 9,
    r1: 0.5,
    n1: 5,
    r2: 2,
    n2: 2,
    ask: "term",
    context: "数が初め9で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_47",
    title: "倍率変更 47",
    a1: 20,
    r1: 2,
    n1: 2,
    r2: 0.8,
    n2: 5,
    ask: "term",
    context: "量が初め20で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_48",
    title: "倍率変更 48",
    a1: 10,
    r1: 0.5,
    n1: 5,
    r2: 2,
    n2: 3,
    ask: "term",
    context: "数が初め10で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_49",
    title: "倍率変更 49",
    a1: 18,
    r1: 2,
    n1: 3,
    r2: 0.5,
    n2: 4,
    ask: "term",
    context: "量が初め18で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_50",
    title: "倍率変更 50",
    a1: 6,
    r1: 3,
    n1: 2,
    r2: 1.5,
    n2: 4,
    ask: "term",
    context: "数が初め6で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_51",
    title: "倍率変更 51",
    a1: 40,
    r1: 0.5,
    n1: 4,
    r2: 2,
    n2: 3,
    ask: "term",
    context: "量が初め40で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_52",
    title: "倍率変更 52",
    a1: 12,
    r1: 2,
    n1: 3,
    r2: 0.8,
    n2: 5,
    ask: "term",
    context: "数が初め12で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_53",
    title: "倍率変更 53",
    a1: 9,
    r1: 0.5,
    n1: 5,
    r2: 1.5,
    n2: 3,
    ask: "term",
    context: "数が初め9で、",
    difficulty: 2,
  },
  {
    id: "seq_ct_geo_change_54",
    title: "倍率変更 54",
    a1: 24,
    r1: 2,
    n1: 2,
    r2: 0.6,
    n2: 4,
    ask: "term",
    context: "量が初め24で、",
    difficulty: 2,
  },
];

export const sequenceCtGeometricChangeTemplates: QuestionTemplate[] = CASES.map(buildTemplate);
