// src/lib/course/templates/math1/prop_proposition_basic.ts
import type { QuestionTemplate } from "../../types";
import { texDivides, texImplies, texNot, texPow, texText } from "@/lib/format/tex";

const evenText = "\\text{偶数}";
const oddText = "\\text{奇数}";

type ChoiceCase = {
  id: string;
  title: string;
  statement: string;
  correct: string;
  choices: string[];
  explain: string;
};

function buildChoice(c: ChoiceCase): QuestionTemplate {
  return {
    meta: {
      id: c.id,
      topicId: "prop_proposition_basic",
      title: c.title,
      difficulty: 1,
      tags: ["logic", "proposition"],
    },
    generate() {
      return {
        templateId: c.id,
        statement: c.statement,
        answerKind: "choice",
        choices: c.choices,
        params: {},
      };
    },
    grade(_params, userAnswer) {
      return { isCorrect: userAnswer === c.correct, correctAnswer: c.correct };
    },
    explain() {
      return c.explain;
    },
  };
}

const P = texDivides(4, "x");
const Q = texDivides(2, "x");

const choiceCases: ChoiceCase[] = [
  {
    id: "prop_conv_1",
    title: "逆命題",
    statement: `命題 $${texImplies(P, Q)}$ の逆命題を選べ。`,
    correct: texImplies(Q, P),
    choices: [
      texImplies(P, Q),
      texImplies(Q, P),
      texImplies(texNot(P), texNot(Q)),
      texImplies(texNot(Q), texNot(P)),
    ],
    explain: `### この問題の解説\n逆命題は $${texImplies(Q, P)}$ です。`,
  },
  {
    id: "prop_inverse_1",
    title: "裏命題",
    statement: `命題 $${texImplies(P, Q)}$ の裏命題を選べ。`,
    correct: texImplies(texNot(P), texNot(Q)),
    choices: [
      texImplies(P, Q),
      texImplies(Q, P),
      texImplies(texNot(P), texNot(Q)),
      texImplies(texNot(Q), texNot(P)),
    ],
    explain: `### この問題の解説\n裏命題は $${texImplies(texNot(P), texNot(Q))}$ です。`,
  },
  {
    id: "prop_contra_1",
    title: "対偶",
    statement: `命題 $${texImplies(P, Q)}$ の対偶を選べ。`,
    correct: texImplies(texNot(Q), texNot(P)),
    choices: [
      texImplies(P, Q),
      texImplies(Q, P),
      texImplies(texNot(P), texNot(Q)),
      texImplies(texNot(Q), texNot(P)),
    ],
    explain: `### この問題の解説\n対偶は $${texImplies(texNot(Q), texNot(P))}$ です。`,
  },
  {
    id: "prop_truth_1",
    title: "真偽判定 1",
    statement: `命題「$x$ が $${evenText}$ ならば $${texPow("x", 2)}$ は $${evenText}$ である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n偶数の二乗は偶数なので真です。`,
  },
  {
    id: "prop_truth_2",
    title: "真偽判定 2",
    statement: `命題「$x$ が $${oddText}$ ならば $${texPow("x", 2)}$ は $${oddText}$ である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n奇数の二乗は奇数なので真です。`,
  },
  {
    id: "prop_truth_3",
    title: "真偽判定 3",
    statement: `命題「$x$ が $4$ の倍数ならば $x$ は $${evenText}$ である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$4$ の倍数は必ず偶数なので真です。`,
  },
  {
    id: "prop_truth_4",
    title: "真偽判定 4",
    statement: `命題「$x$ が $${evenText}$ ならば $${texDivides(4, "x")}$ である」は真か偽か。`,
    correct: texText("偽"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n偶数でも $6$ のように $4$ の倍数でない例があるため偽です。`,
  },
  {
    id: "prop_nec_suf_1",
    title: "必要十分 1",
    statement: `$A: ${P}$、$B: ${Q}$ とする。$A$ は $B$ の何条件か。`,
    correct: texText("十分条件"),
    choices: [texText("必要条件"), texText("十分条件"), texText("必要十分条件"), texText("どれでもない")],
    explain: `### この問題の解説\n$A \\Rightarrow B$ なので $A$ は $B$ の十分条件です。`,
  },
  {
    id: "prop_nec_suf_2",
    title: "必要十分 2",
    statement: `$A: ${Q}$、$B: ${P}$ とする。$A$ は $B$ の何条件か。`,
    correct: texText("必要条件"),
    choices: [texText("必要条件"), texText("十分条件"), texText("必要十分条件"), texText("どれでもない")],
    explain: `### この問題の解説\n$B \\Rightarrow A$ なので $A$ は $B$ の必要条件です。`,
  },
  {
    id: "prop_negation_1",
    title: "否定 1",
    statement: `命題「すべての整数 $x$ について $${texPow("x", 2)} \\ge 0$」の否定を選べ。`,
    correct: "\\text{ある整数 }x\\text{ が存在して }x^2 < 0",
    choices: [
      "\\text{ある整数 }x\\text{ が存在して }x^2 < 0",
      "\\text{すべての整数 }x\\text{ について }x^2 < 0",
      "\\text{ある整数 }x\\text{ が存在して }x^2 \\ge 0",
      "\\text{すべての整数 }x\\text{ について }x^2 \\ge 0",
    ],
    explain: `### この問題の解説\n全称命題の否定は「存在して〜でない」です。`,
  },
  {
    id: "prop_negation_2",
    title: "否定 2",
    statement: `命題「ある整数 $x$ が存在して $x$ は $${evenText}$ である」の否定を選べ。`,
    correct: "\\text{すべての整数 }x\\text{ について }x\\text{ は奇数である}",
    choices: [
      "\\text{すべての整数 }x\\text{ について }x\\text{ は奇数である}",
      "\\text{ある整数 }x\\text{ が存在して }x\\text{ は奇数である}",
      "\\text{すべての整数 }x\\text{ について }x\\text{ は偶数である}",
      "\\text{ある整数 }x\\text{ が存在して }x\\text{ は偶数である}",
    ],
    explain: `### この問題の解説\n存在命題の否定は「すべて〜でない」です。`,
  },
  {
    id: "prop_contra_2",
    title: "対偶 2",
    statement: `命題「$x$ が $${oddText}$ ならば $${texPow("x", 2)}$ は $${oddText}$ である」の対偶を選べ。`,
    correct: texImplies(texNot("x^2\\text{は奇数}"), texNot("x\\text{は奇数}")),
    choices: [
      texImplies("x\\text{は奇数}", "x^2\\text{は奇数}"),
      texImplies("x^2\\text{は奇数}", "x\\text{は奇数}"),
      texImplies(texNot("x\\text{は奇数}"), texNot("x^2\\text{は奇数}")),
      texImplies(texNot("x^2\\text{は奇数}"), texNot("x\\text{は奇数}")),
    ],
    explain: `### この問題の解説\n対偶は否定を入れ替えた命題です。`,
  },
  {
    id: "prop_conv_2",
    title: "逆命題 2",
    statement: `命題「$x$ が $3$ の倍数ならば $x$ は $6$ の倍数である」の逆命題を選べ。`,
    correct: texImplies(texDivides(6, "x"), texDivides(3, "x")),
    choices: [
      texImplies(texDivides(3, "x"), texDivides(6, "x")),
      texImplies(texDivides(6, "x"), texDivides(3, "x")),
      texImplies(texNot(texDivides(3, "x")), texNot(texDivides(6, "x"))),
      texImplies(texNot(texDivides(6, "x")), texNot(texDivides(3, "x"))),
    ],
    explain: `### この問題の解説\n逆命題は結論と条件を入れ替えます。`,
  },
  {
    id: "prop_suf_1",
    title: "十分条件",
    statement: `$A: ${texDivides(6, "x")}$、$B: ${texDivides(3, "x")}$ とする。$A$ は $B$ の何条件か。`,
    correct: texText("十分条件"),
    choices: [texText("必要条件"), texText("十分条件"), texText("必要十分条件"), texText("どれでもない")],
    explain: `### この問題の解説\n$6$ の倍数なら $3$ の倍数なので十分条件です。`,
  },
  {
    id: "prop_nec_1",
    title: "必要条件",
    statement: `$A: ${texDivides(5, "x")}$、$B: ${texDivides(10, "x")}$ とする。$A$ は $B$ の何条件か。`,
    correct: texText("必要条件"),
    choices: [texText("必要条件"), texText("十分条件"), texText("必要十分条件"), texText("どれでもない")],
    explain: `### この問題の解説\n$10$ の倍数なら $5$ の倍数なので必要条件です。`,
  },
  {
    id: "prop_truth_5",
    title: "真偽判定 5",
    statement: `命題「$x$ が $6$ の倍数ならば $x$ は $3$ の倍数である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$6$ の倍数は必ず $3$ の倍数です。`,
  },
  {
    id: "prop_truth_6",
    title: "真偽判定 6",
    statement: `命題「$x$ が $3$ の倍数ならば $x$ は $6$ の倍数である」は真か偽か。`,
    correct: texText("偽"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$3$ の倍数でも $9$ のように $6$ の倍数でない例があるため偽です。`,
  },
  {
    id: "prop_negation_3",
    title: "否定 3",
    statement: `命題「すべての自然数 $x$ について $x+1 > x$」の否定を選べ。`,
    correct: "\\text{ある自然数 }x\\text{ が存在して }x+1 \\le x",
    choices: [
      "\\text{ある自然数 }x\\text{ が存在して }x+1 \\le x",
      "\\text{すべての自然数 }x\\text{ について }x+1 \\le x",
      "\\text{ある自然数 }x\\text{ が存在して }x+1 > x",
      "\\text{すべての自然数 }x\\text{ について }x+1 > x",
    ],
    explain: `### この問題の解説\n全称命題の否定は「存在して〜でない」です。`,
  },
  {
    id: "prop_contra_3",
    title: "対偶 3",
    statement: `命題「$${texDivides(6, "x")}$ ならば $x$ は $${evenText}$ である」の対偶を選べ。`,
    correct: texImplies(texNot("x\\text{は偶数}"), texNot(texDivides(6, "x"))),
    choices: [
      texImplies(texDivides(6, "x"), "x\\text{は偶数}"),
      texImplies("x\\text{は偶数}", texDivides(6, "x")),
      texImplies(texNot(texDivides(6, "x")), texNot("x\\text{は偶数}")),
      texImplies(texNot("x\\text{は偶数}"), texNot(texDivides(6, "x"))),
    ],
    explain: `### この問題の解説\n対偶は否定を入れ替えます。`,
  },
  {
    id: "prop_nec_suf_3",
    title: "必要十分 3",
    statement: `$A: x=0$、$B: x^2=0$ とする。$A$ は $B$ の何条件か。`,
    correct: texText("必要十分条件"),
    choices: [texText("必要条件"), texText("十分条件"), texText("必要十分条件"), texText("どれでもない")],
    explain: `### この問題の解説\n$x=0$ と $x^2=0$ は同値なので必要十分条件です。`,
  },
  {
    id: "prop_truth_7",
    title: "真偽判定 7",
    statement: `命題「$x$ が $8$ の倍数ならば $x$ は $4$ の倍数である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$8$ の倍数は必ず $4$ の倍数です。`,
  },
  {
    id: "prop_truth_8",
    title: "真偽判定 8",
    statement: `命題「$x$ が $4$ の倍数ならば $x$ は $8$ の倍数である」は真か偽か。`,
    correct: texText("偽"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$4$ の倍数でも $12$ のように $8$ の倍数でない例があるため偽です。`,
  },
  {
    id: "prop_truth_9",
    title: "真偽判定 9",
    statement: `命題「$x$ が $${evenText}$ ならば $${texPow("x", 2)}$ は $${oddText}$ である」は真か偽か。`,
    correct: texText("偽"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n偶数の二乗は偶数なので偽です。`,
  },
  {
    id: "prop_nec_suf_4",
    title: "必要十分 4",
    statement: `$A: ${texDivides(12, "x")}$、$B: ${texDivides(3, "x")}$ とする。$A$ は $B$ の何条件か。`,
    correct: texText("十分条件"),
    choices: [texText("必要条件"), texText("十分条件"), texText("必要十分条件"), texText("どれでもない")],
    explain: `### この問題の解説\n$12$ の倍数なら必ず $3$ の倍数なので十分条件です。`,
  },
  {
    id: "prop_nec_suf_5",
    title: "必要十分 5",
    statement: `$A: ${texDivides(3, "x")}$、$B: ${texDivides(12, "x")}$ とする。$A$ は $B$ の何条件か。`,
    correct: texText("必要条件"),
    choices: [texText("必要条件"), texText("十分条件"), texText("必要十分条件"), texText("どれでもない")],
    explain: `### この問題の解説\n$12$ の倍数なら必ず $3$ の倍数なので必要条件です。`,
  },
  {
    id: "prop_negation_4",
    title: "否定 4",
    statement: `命題「すべての整数 $x$ について $x$ は $${evenText}$ である」の否定を選べ。`,
    correct: "\\text{ある整数 }x\\text{ が存在して }x\\text{ は偶数でない}",
    choices: [
      "\\text{ある整数 }x\\text{ が存在して }x\\text{ は偶数でない}",
      "\\text{ある整数 }x\\text{ が存在して }x\\text{ は偶数である}",
      "\\text{すべての整数 }x\\text{ について }x\\text{ は偶数でない}",
      "\\text{すべての整数 }x\\text{ について }x\\text{ は偶数である}",
    ],
    explain: `### この問題の解説\n全称命題の否定は「存在して〜でない」です。`,
  },
  {
    id: "prop_negation_5",
    title: "否定 5",
    statement: `命題「ある整数 $x$ が存在して $x$ は $${oddText}$ である」の否定を選べ。`,
    correct: "\\text{すべての整数 }x\\text{ について }x\\text{ は奇数でない}",
    choices: [
      "\\text{すべての整数 }x\\text{ について }x\\text{ は奇数でない}",
      "\\text{すべての整数 }x\\text{ について }x\\text{ は奇数である}",
      "\\text{ある整数 }x\\text{ が存在して }x\\text{ は奇数でない}",
      "\\text{ある整数 }x\\text{ が存在して }x\\text{ は奇数である}",
    ],
    explain: `### この問題の解説\n存在命題の否定は「すべて〜でない」です。`,
  },
  {
    id: "prop_contra_4",
    title: "対偶 4",
    statement: `命題「$${texDivides(9, "x")}$ ならば $x$ は $${texDivides(3, "x")}$ である」の対偶を選べ。`,
    correct: texImplies(texNot(texDivides(3, "x")), texNot(texDivides(9, "x"))),
    choices: [
      texImplies(texDivides(9, "x"), texDivides(3, "x")),
      texImplies(texDivides(3, "x"), texDivides(9, "x")),
      texImplies(texNot(texDivides(9, "x")), texNot(texDivides(3, "x"))),
      texImplies(texNot(texDivides(3, "x")), texNot(texDivides(9, "x"))),
    ],
    explain: `### この問題の解説\n対偶は否定を入れ替えた命題です。`,
  },
  {
    id: "prop_ext_1",
    title: "逆命題 6",
    statement: `命題「$x$ が $6$ の倍数ならば $x$ は $3$ の倍数である」の逆命題を選べ。`,
    correct: texImplies(texDivides(3, "x"), texDivides(6, "x")),
    choices: [
      texImplies(texDivides(6, "x"), texDivides(3, "x")),
      texImplies(texDivides(3, "x"), texDivides(6, "x")),
      texImplies(texNot(texDivides(6, "x")), texNot(texDivides(3, "x"))),
      texImplies(texNot(texDivides(3, "x")), texNot(texDivides(6, "x"))),
    ],
    explain: `### この問題の解説\n逆命題は結論と条件を入れ替えます。`,
  },
  {
    id: "prop_ext_2",
    title: "裏命題 4",
    statement: `命題「$x$ が $8$ の倍数ならば $x$ は $4$ の倍数である」の裏命題を選べ。`,
    correct: texImplies(texNot(texDivides(8, "x")), texNot(texDivides(4, "x"))),
    choices: [
      texImplies(texDivides(8, "x"), texDivides(4, "x")),
      texImplies(texDivides(4, "x"), texDivides(8, "x")),
      texImplies(texNot(texDivides(8, "x")), texNot(texDivides(4, "x"))),
      texImplies(texNot(texDivides(4, "x")), texNot(texDivides(8, "x"))),
    ],
    explain: `### この問題の解説\n裏命題は条件と結論を否定します。`,
  },
  {
    id: "prop_ext_3",
    title: "対偶 5",
    statement: `命題「$x$ が $5$ の倍数ならば $x$ は $10$ の倍数である」の対偶を選べ。`,
    correct: texImplies(texNot(texDivides(10, "x")), texNot(texDivides(5, "x"))),
    choices: [
      texImplies(texDivides(5, "x"), texDivides(10, "x")),
      texImplies(texDivides(10, "x"), texDivides(5, "x")),
      texImplies(texNot(texDivides(5, "x")), texNot(texDivides(10, "x"))),
      texImplies(texNot(texDivides(10, "x")), texNot(texDivides(5, "x"))),
    ],
    explain: `### この問題の解説\n対偶は条件と結論を入れ替えて否定します。`,
  },
  {
    id: "prop_ext_4",
    title: "真偽判定 10",
    statement: `命題「$x$ が $10$ の倍数ならば $x$ は偶数である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$10$ の倍数は必ず偶数です。`,
  },
  {
    id: "prop_ext_5",
    title: "真偽判定 11",
    statement: `命題「$x$ が偶数ならば $x$ は $10$ の倍数である」は真か偽か。`,
    correct: texText("偽"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n偶数でも $2,4,6$ のように $10$ の倍数でない例があります。`,
  },
  {
    id: "prop_ext_6",
    title: "真偽判定 12",
    statement: `命題「$x$ が $12$ の倍数ならば $x$ は $6$ の倍数である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$12$ の倍数は必ず $6$ の倍数です。`,
  },
  {
    id: "prop_ext_7",
    title: "真偽判定 13",
    statement: `命題「$x$ が $12$ の倍数ならば $x$ は $8$ の倍数である」は真か偽か。`,
    correct: texText("偽"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$12$ の倍数でも $12$ のように $8$ の倍数でない例があります。`,
  },
  {
    id: "prop_ext_8",
    title: "真偽判定 14",
    statement: `命題「$x$ が $15$ の倍数ならば $x$ は $5$ の倍数である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$15$ の倍数は必ず $5$ の倍数です。`,
  },
  {
    id: "prop_ext_9",
    title: "真偽判定 15",
    statement: `命題「$x$ が $5$ の倍数ならば $x$ は $15$ の倍数である」は真か偽か。`,
    correct: texText("偽"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$5$ の倍数でも $5,10$ のように $15$ の倍数でない例があります。`,
  },
  {
    id: "prop_ext_10",
    title: "必要十分 6",
    statement: `$A: ${texDivides(8, "x")}$、$B: x\\text{ は偶数}$ とする。$A$ は $B$ の何条件か。`,
    correct: texText("十分条件"),
    choices: [texText("必要条件"), texText("十分条件"), texText("必要十分条件"), texText("どれでもない")],
    explain: `### この問題の解説\n$8$ の倍数なら偶数なので十分条件です。`,
  },
  {
    id: "prop_ext_11",
    title: "必要十分 7",
    statement: `$A: x\\text{ は偶数}$、$B: ${texDivides(8, "x")}$ とする。$A$ は $B$ の何条件か。`,
    correct: texText("必要条件"),
    choices: [texText("必要条件"), texText("十分条件"), texText("必要十分条件"), texText("どれでもない")],
    explain: `### この問題の解説\n$8$ の倍数なら偶数なので必要条件です。`,
  },
  {
    id: "prop_ext_12",
    title: "否定 6",
    statement: `命題「すべての整数 $x$ について $x^2\\ge 0$」の否定を選べ。`,
    correct: "\\text{ある整数 }x\\text{ が存在して }x^2<0",
    choices: [
      "\\text{ある整数 }x\\text{ が存在して }x^2<0",
      "\\text{ある整数 }x\\text{ が存在して }x^2\\ge 0",
      "\\text{すべての整数 }x\\text{ について }x^2<0",
      "\\text{すべての整数 }x\\text{ について }x^2\\ge 0",
    ],
    explain: `### この問題の解説\n全称命題の否定は「存在して〜でない」です。`,
  },
  {
    id: "prop_ext_13",
    title: "否定 7",
    statement: `命題「ある整数 $x$ が存在して $x$ は $4$ の倍数である」の否定を選べ。`,
    correct: "\\text{すべての整数 }x\\text{ について }x\\text{ は }4\\text{ の倍数でない}",
    choices: [
      "\\text{すべての整数 }x\\text{ について }x\\text{ は }4\\text{ の倍数でない}",
      "\\text{すべての整数 }x\\text{ について }x\\text{ は }4\\text{ の倍数である}",
      "\\text{ある整数 }x\\text{ が存在して }x\\text{ は }4\\text{ の倍数でない}",
      "\\text{ある整数 }x\\text{ が存在して }x\\text{ は }4\\text{ の倍数である}",
    ],
    explain: `### この問題の解説\n存在命題の否定は「すべて〜でない」です。`,
  },
  {
    id: "prop_ext_14",
    title: "対偶 6",
    statement: `命題「$x$ が奇数ならば $x^2$ は奇数である」の対偶を選べ。`,
    correct: texImplies(texNot("x^2\\text{は奇数}"), texNot("x\\text{は奇数}")),
    choices: [
      texImplies("x\\text{は奇数}", "x^2\\text{は奇数}"),
      texImplies("x^2\\text{は奇数}", "x\\text{は奇数}"),
      texImplies(texNot("x\\text{は奇数}"), texNot("x^2\\text{は奇数}")),
      texImplies(texNot("x^2\\text{は奇数}"), texNot("x\\text{は奇数}")),
    ],
    explain: `### この問題の解説\n対偶は条件と結論を入れ替えて否定します。`,
  },
  {
    id: "prop_ext_15",
    title: "逆命題 7",
    statement: `命題「$x$ が $9$ の倍数ならば $x$ は $3$ の倍数である」の逆命題を選べ。`,
    correct: texImplies(texDivides(3, "x"), texDivides(9, "x")),
    choices: [
      texImplies(texDivides(9, "x"), texDivides(3, "x")),
      texImplies(texDivides(3, "x"), texDivides(9, "x")),
      texImplies(texNot(texDivides(9, "x")), texNot(texDivides(3, "x"))),
      texImplies(texNot(texDivides(3, "x")), texNot(texDivides(9, "x"))),
    ],
    explain: `### この問題の解説\n逆命題は結論と条件を入れ替えます。`,
  },
  {
    id: "prop_ext_16",
    title: "裏命題 5",
    statement: `命題「$x$ が $9$ の倍数ならば $x$ は $3$ の倍数である」の裏命題を選べ。`,
    correct: texImplies(texNot(texDivides(9, "x")), texNot(texDivides(3, "x"))),
    choices: [
      texImplies(texDivides(9, "x"), texDivides(3, "x")),
      texImplies(texDivides(3, "x"), texDivides(9, "x")),
      texImplies(texNot(texDivides(9, "x")), texNot(texDivides(3, "x"))),
      texImplies(texNot(texDivides(3, "x")), texNot(texDivides(9, "x"))),
    ],
    explain: `### この問題の解説\n裏命題は条件と結論を否定します。`,
  },
  {
    id: "prop_ext_17",
    title: "真偽判定 16",
    statement: `命題「$x$ が $7$ の倍数ならば $x$ は $14$ の倍数である」は真か偽か。`,
    correct: texText("偽"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$7$ の倍数でも $7,21$ のように $14$ の倍数でない例があります。`,
  },
  {
    id: "prop_ext_18",
    title: "真偽判定 17",
    statement: `命題「$x$ が $14$ の倍数ならば $x$ は $7$ の倍数である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$14$ の倍数は必ず $7$ の倍数です。`,
  },
  {
    id: "prop_ext_19",
    title: "真偽判定 18",
    statement: `命題「$x$ が奇数ならば $x^3$ は奇数である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n奇数の3乗は奇数です。`,
  },
  {
    id: "prop_ext_20",
    title: "真偽判定 19",
    statement: `命題「$x$ が偶数ならば $x^3$ は偶数である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n偶数の3乗は偶数です。`,
  },
  {
    id: "prop_ext_21",
    title: "必要十分 8",
    statement: `$A: x=0$、$B: x^3=0$ とする。$A$ は $B$ の何条件か。`,
    correct: texText("必要十分条件"),
    choices: [texText("必要条件"), texText("十分条件"), texText("必要十分条件"), texText("どれでもない")],
    explain: `### この問題の解説\n$x=0$ と $x^3=0$ は同値なので必要十分条件です。`,
  },
  {
    id: "prop_ext_22",
    title: "真偽判定 20",
    statement: `命題「$x^2$ が偶数ならば $x$ は偶数である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$x$ が奇数なら $x^2$ も奇数なので、偶数になることはありません。`,
  },
  {
    id: "prop_ext_23",
    title: "真偽判定 21",
    statement: `命題「$x^2$ が奇数ならば $x$ は奇数である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n偶数の二乗は偶数なので、奇数なら元も奇数です。`,
  },
  {
    id: "prop_ext_24",
    title: "真偽判定 22",
    statement: `命題「$x$ が偶数ならば $x^2$ は奇数である」は真か偽か。`,
    correct: texText("偽"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n偶数の二乗は偶数なので偽です。`,
  },
  {
    id: "prop_ext_25",
    title: "必要十分 9",
    statement: `$A: ${texDivides(3, "x")}$、$B: ${texDivides(3, "x^2")}$ とする。$A$ は $B$ の何条件か。`,
    correct: texText("必要十分条件"),
    choices: [texText("必要条件"), texText("十分条件"), texText("必要十分条件"), texText("どれでもない")],
    explain: `### この問題の解説\n$x$ が3の倍数 ⇔ $x^2$ が3の倍数なので必要十分条件です。`,
  },
  {
    id: "prop_ext_26",
    title: "逆命題 8",
    statement: `命題「$x$ が偶数ならば $x^2$ は偶数である」の逆命題を選べ。`,
    correct: texImplies("x^2\\text{は偶数}", "x\\text{は偶数}"),
    choices: [
      texImplies("x\\text{は偶数}", "x^2\\text{は偶数}"),
      texImplies("x^2\\text{は偶数}", "x\\text{は偶数}"),
      texImplies(texNot("x\\text{は偶数}"), texNot("x^2\\text{は偶数}")),
      texImplies(texNot("x^2\\text{は偶数}"), texNot("x\\text{は偶数}")),
    ],
    explain: `### この問題の解説\n逆命題は結論と条件を入れ替えます。`,
  },
  {
    id: "prop_ext_27",
    title: "裏命題 6",
    statement: `命題「$x$ が偶数ならば $x^2$ は偶数である」の裏命題を選べ。`,
    correct: texImplies(texNot("x\\text{は偶数}"), texNot("x^2\\text{は偶数}")),
    choices: [
      texImplies("x\\text{は偶数}", "x^2\\text{は偶数}"),
      texImplies("x^2\\text{は偶数}", "x\\text{は偶数}"),
      texImplies(texNot("x\\text{は偶数}"), texNot("x^2\\text{は偶数}")),
      texImplies(texNot("x^2\\text{は偶数}"), texNot("x\\text{は偶数}")),
    ],
    explain: `### この問題の解説\n裏命題は条件と結論を否定します。`,
  },
  {
    id: "prop_ext_28",
    title: "真偽判定 23",
    statement: `命題「$x$ が $4$ の倍数ならば $x$ は $2$ の倍数である」は真か偽か。`,
    correct: texText("真"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$4$ の倍数は必ず $2$ の倍数です。`,
  },
  {
    id: "prop_ext_29",
    title: "真偽判定 24",
    statement: `命題「$x$ が $2$ の倍数ならば $x$ は $4$ の倍数である」は真か偽か。`,
    correct: texText("偽"),
    choices: [texText("真"), texText("偽")],
    explain: `### この問題の解説\n$2$ の倍数でも $2,6$ のように $4$ の倍数でない例があります。`,
  },
  {
    id: "prop_ext_30",
    title: "必要十分 10",
    statement: `$A: ${texDivides(9, "x")}$、$B: ${texDivides(3, "x")}$ とする。$A$ は $B$ の何条件か。`,
    correct: texText("十分条件"),
    choices: [texText("必要条件"), texText("十分条件"), texText("必要十分条件"), texText("どれでもない")],
    explain: `### この問題の解説\n$9$ の倍数なら $3$ の倍数なので十分条件です。`,
  },
];

export const propPropositionTemplates: QuestionTemplate[] = choiceCases.map(buildChoice);
